### ISSUE TITLE
Improve mobile user-agent identification

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1010]
Currently, we set `uaDeviceType` to `'mobile'` if [ua-parser](https://www.npmjs.com/package/ua-parser) returns something other than `'Other'` for its `device.family` property.

Although this approach doesn't produce any false positives, it does let a lot of valid mobile devices through the net. I used [this list](http://www.useragentstring.com/pages/Mobile%20Browserlist/) and ran a bunch of tests in the repl.

Most significantly, I found that:

* None of the user-agent strings for Fennec identified a device type.
* None of the user-agent strings for IE mobile identified a device type.
* None of the user-agent strings for Opera Mini identified a device type.

A better heuristic would be to additionally take the `os.family` property into account. Comparing that to a known mobile OS (specifically `'Android'` for the cases I tested, but we can have a wider list than that), should let us catch more mobile devices.

**Comment by rfk** [comment]
In discussing this with @philbooth we decided that it's small enough and closely-related-enough to our core active stories that it should go straight into "now" status.  At the very least, we should ensure that Fennec gets identified as a mobile device, otherwise any mobile-related metrics will be too inaccurate to be of any use.
