### ISSUE TITLE
Work breakdown for user retention measurement

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1011]
Opening this issue to collect and discuss thoughts on how to implement https://github.com/mozilla/fxa/issues/45, which describes a user retention curve with points plotted at days 0, 1, 3, 7, 14, 30, 60 and 90.

My [initial suggestion](https://github.com/mozilla/fxa-auth-db-mysql/issues/75), relying on `lastAccessTime`, was insufficiently precise. Instead it seems likely that we'll need to separately store each day of activity for retained users as events in their own right. Doing so will better enable us to make comparisons between different groups of users and over time.

**Comment by philbooth** [comment]
Pulling this into the `now` column for visibility. I'm kind-of-working on it this sprint, but the outcome may only be more concrete issues to work on later.

**Comment by rfk** [comment]
>  separately store each day of activity 

Possiblye s/store/emit/ as I don't think we will need to keep this information once it's aggregated for metrics purposes, at least not initially.

**Comment by philbooth** [comment]
@rfk, I was looking at the `processUnpublishedEvents` stuff and the `eventLog` table yesterday. I'm assuming those events correspond to account activity; I can see it contains values like `create`, `verify`, `reset` and `delete` in my local database and they get published to the `notifications.publishUrl` config setting / `NOTIFICATIONS_PUBLISH_URL` environment variable.

Can that mechanism be appropriated for these retention events, or would that be inappropriate for whatever reason? Where do those events actually end up going to?

**Comment by rfk** [comment]
These correspond to account *lifecycle* events, i.e. things that change the state of the account itself.  The existing ones don't occur frequently enough for our purposes, e.g. there's no lifecycle event for "I showed up and synced my account today".

> Where do those events actually end up going to?

Currently nowhere.  The idea is that we can feed these into a system to notify reliers of the change [1], e.g. "user ABC deleted their account, you should delete any data stored for them" or "user XYZ changed their account, refresh any cached data you might have".  That part of the work is currently de-prioritized but we'll cycle back to it at some point.

> Can that mechanism be appropriated for these retention events

It's probably too heavyweight on the storage front to be a good fit here.  Especially for deletion events, it's important that we don't lose track of any, which is why they're written into that queueing table in the DB as part of the same transaction that does the delete.  We don't need that sort of guarantee for more general metrics stuff.

[1] https://github.com/mozilla/fxa-notification-server

**Comment by philbooth** [comment]
Raised https://github.com/mozilla/fxa-auth-db-mysql/issues/85, https://github.com/mozilla/fxa-auth-db-mysql/issues/86 and https://github.com/mozilla/fxa-auth-db-mysql/issues/87 to cover this, closing.
