### ISSUE TITLE
Reduce write load of updating session-token metadata

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1044]
The recent change to track UA/access-time metadata for session tokens seems to have dramatically increased the write load on the database, such that we're now using about half the privisioned write IOPS on the database.  That's OK for a spell, but we should try to reduce it so that we've got headroom for other things in future.

One idea might be to gather the updates in memory and write them out in batches, rather than sending each one individually.

**Comment by rfk** [comment]
Bumping this to `waffle:next` because #1169

**Comment by rfk** [comment]
removing the heart because we disabled this in production for now, but leaving it in next

**Comment by vladikoff** [comment]
from mtg: needs plan

**Comment by rfk** [comment]
We still need to figure out a way forward for this.  Some musings below...

We have memcache on the auth-server now, perhaps we can just store these timestamps in memcache rather than writing them to the DB.  We could even consider a two-level approach where we write into the DB with lower granularity, and keep higher-precision timestamps in memcached.

Or, we could try to store them in a separate table that's optimized for frequent writes and occasional reads, rather than the other way around.  Perhaps a simple (timestamp, uid, sessionId) table to which items are appended in timestamp order.  This should be cheaper to write to, but you'd have to do a big old range scan in order to locate the most recent timestamp for a particular sessionId.

@philbooth have you had any further thoughts on this since the last time we looked at it?

**Comment by philbooth** [comment]
> @philbooth have you had any further thoughts on this since the last time we looked at it?

I haven't even tried to have them! Having them now though, happy to put my face on this unless anyone else wants it.

> perhaps we can just store these timestamps in memcache rather than writing them to the DB. We could even consider a two-level approach where we write into the DB with lower granularity, and keep higher-precision timestamps in memcached.

I like the idea of getting memcached involved (I guess it would mean having a dedicated instance for auth server stuff so that we don't overload the customs server instance). Anyway, I'll pursue this avenue first.

**Comment by vladikoff** [comment]
from mtg: ping @philbooth

**Comment by vladikoff** [comment]
@philbooth did you have any recent updates / ideas / plans for this?

**Comment by philbooth** [comment]
> did you have any recent updates / ideas / plans for this?

It is absolutely still on my to-do list sorry, just some other things are slightly higher priority right now.

I have three different vague ideas for tackling it, none of which I've fully investigated against actual data yet. @rfk made the point that the best way to approach it would be to get simplest solution in place behind a feature flag then iterate from there as necessary.

So, with the simplest solution first, my three potential ideas were:

1. Write updates to memcached, say, 9 times out of 10 per user and only every 10th time into the db. Then, when we fetch session tokens, we also fetch from memcached and compare the last updated times to see which data we should return.

2. Add a new table to the database with `ENGINE=MEMORY`, call it `sessionTokenUpdates`, send updates to that rather than `sessionTokens`. Periodically batch update `sessionTokens` from `sessionTokenUpdates`.

3. Kind of a hybrid of `1` and `2`. Store the updates in memcached then periodically generate a big batch query (don't think it can be a stored procedure) to update `sessionTokens`.

**Comment by philbooth** [comment]
> ...my three potential ideas were...

(I think `2` is my favourite, fwiw)

**Comment by philbooth** [comment]
Back-of-an-envelope calculation for the cost of leaning on memcached for this, with the caveat that I don't have the faintest idea what I'm talking about:

* The data we're storing is a number, 64 bits, so 8 bytes for that.

* Based on a few minutes reading StackOverflow and Wikipedia, I *think* memcached keys are hashed to 128 bits, so 16 bytes for that.

* We have ~6 million DAU.

* So, if we were to store `lastAccessTime` for 6 million users all at the same time in memcached, it would consume 144,000,000 bytes, or 140,625 kilobytes, or 137 megabytes.

* Obviously, the lifetime that's set for this data would affect that value. For this feature, I'm not certain what a sensible lifetime would be yet.

**Comment by vladikoff** [comment]
from mtg: 

* switch the [db.updateSessionToken](https://github.com/mozilla/fxa-auth-server/blob/13eeab2b89de915589d59c2e6a92b7eccebf46d4/lib/db.js#L476) to redis
* use a different redis instance than the profile cacher (cc @jbuck). However really similar configuration options to the profile server 
* roll out strategy, slow rollout based on sessionToken id as seed (first rollout 30%)

**Comment by vladikoff** [comment]
This is where the `update` happens: https://github.com/mozilla/fxa-auth-server/blob/470387fc24f13449a6602be4e3885e1ee7341228/lib/routes/sign.js#L53

**Comment by vladikoff** [comment]
from mtg: 

* @rfk  should we do a slow roll out to just mozilla / restmail users or just key off uid / sessionToken 
*

**Comment by rfk** [comment]
Keying off the uid seems reasonable to me, I don't think we'll learn anything terribly interesting from rolling out only to Mozilla users.
