### ISSUE TITLE
FXA-57: Figure out how to measure the "Reminder to Verify" email

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1082]
Probably using retention metrics and activity events

Related: https://github.com/mozilla/fxa-auth-server/issues/1081

**Comment by rfk** [comment]
Since the ultimate measure of success here is "the user successfully connected to sync", seeing a successful `account.signed` event seems like a good concrete metric to measure.  Something like "of the number of people we send a reminder email to, what percentage subsequently perform an `account.signed`"?

**Comment by vladikoff** [comment]
This is documented in https://github.com/mozilla/fxa/tree/master/features/FxA-57-verify-reminder#success-criteria
