### ISSUE TITLE
conventional changelog omits some commits

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1152]
1. it entirely skips commits with 'blah(bleh):' with no error or warning

2. only recognizes feat/fix/perf/revert/refactor. I know this is by design. I also disagree that it should not  reflect the full commit history ;-)

**Comment by vladikoff** [comment]
See out changelog transform template here: https://github.com/vladikoff/fxa-conventional-changelog/blob/master/index.js#L23

**Comment by pdehaan** [comment]
Yeah, i think that rogue `return` on [line 35](https://github.com/vladikoff/fxa-conventional-changelog/blob/226d7807ced85b8244b4c301302e2259974a4748/index.js#L35) is the culprit.

I tried hacking this locally and changing the writerOpts transform to exit early if there was a null `commit.type` (since that seems to be a merged branch or PR), and then just letting the rest of the commits fall through.

I regenerated the CHANGELOG.md file with the last 15 releases (it freezes somewhere between 15 and 20 releases for me) and it looks like the only new additions to the CHANGELOG were all (~20) of our `chore(*)` commits, as well as one `cleanup(test):` and one `style(indent):` commits. I [quickly] counted and got about 22 new commits in the changelog, so it wasn't too distracting and there were some interesting results.

+1 for full commit history.

**Comment by pdehaan** [comment]
PR filed at https://github.com/vladikoff/fxa-conventional-changelog/pull/4

Feel free to laugh and throw it into the abyss.

**Comment by jrgm** [comment]
So this is maybe fixed now (??)

**Comment by vladikoff** [comment]
@jrgm I'll take a look at it
