### ISSUE TITLE
Emit new activity events for KPI dashboards

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1199]
As part of [1] we'll need the following new activity events:

* "device.created": emitted when a device record is successfully created
* "device.deleted": emitted when a device record is successfully deleted
* "account.keyfetch": emitted when encryption keys are successfully fetched"

These should all include a `device_id` property giving the device-id if available.

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards

**Comment by philbooth** [comment]
Is this a partial dup of #1186? The `device.created` and `device.deleted` events I mean.

**Comment by rfk** [comment]
IIUC #1186 wants the events to go out over SNS so that sync can see then, which is a different event stream to what we're considering here.  (We might look at trying to merge the two streams, as they also emit very similar e.g. login events; but that's a separate bug)

**Comment by philbooth** [comment]
Hey @jrgm, I have some questions for you, apologies if they're stupid ones.

Part of this issue requires that we associate the metrics metadata from https://github.com/mozilla/fxa-auth-server/pull/1213 with the session token in some kind of memory store (redis/memcached/whatever), so that the auth server can add it to these new activity events. The metadata can't be made available via the relevant endpoints because they're invoked by the browser code, which doesn't have access to said metadata.

Is an appropriate store available within our infrastructure? If so, what are the details? Or if not, what's needed to set one up and what can I do to assist?
