### ISSUE TITLE
Using NSP in pull requests

### ISSUE THREAD

**Issue by jvehent** [mozilla/fxa-auth-server#1240]
Following a [post](https://twitter.com/adam_baldwin/status/724984039883608064) by @evilpacket where mozilla is mentioned using NSP, I started looking at how we use it in fxa-auth-server. I'm curious about the developer feedback around it. Is it useful? Should we do more with it? Does it help keeping track of dependencies? Does it have issues.  @jbuck mentioned that it doesn't appear to be integrated with pull requests today, and I'm wondering why that is.

I'm looking for a dependency management solution we could standardize across NodeJS projects, so I'm very interested in feedback around nsp.

**Comment by vladikoff** [comment]
>  @jbuck mentioned that it doesn't appear to be integrated with pull requests today, and I'm wondering why that is.

It is integrated here: https://travis-ci.org/mozilla/fxa-auth-server/jobs/125742327#L677

See 

```
1.64s$ grunt nsp --force
Running "nsp" task
Warning: (+) 5 vulnerabilities found
 Name     Installed   Patched    Path                                                              More Info                             
 moment   2.10.6      >=2.11.2   fxa-auth-server@1.59.0 > convict@1.0.1 > moment@2.10.6            https://nodesecurity.io/advisories/55 
 hapi     8.8.1       >=11.1.4   fxa-auth-server@1.59.0 > hapi@8.8.1                               https://nodesecurity.io/advisories/65 
 hapi     8.8.1       >=11.0.0   fxa-auth-server@1.59.0 > hapi@8.8.1                               https://nodesecurity.io/advisories/45 
 hapi     8.8.1       >=11.1.3   fxa-auth-server@1.59.0 > hapi@8.8.1                               https://nodesecurity.io/advisories/63 
 moment   2.10.3      >=2.11.2   fxa-auth-server@1.59.0 > hapi@8.8.1 > joi@6.4.1 > moment@2.10.3   https://nodesecurity.io/advisories/55 
 Used --force, continuing.
Done, but with warnings.
```

Most times in the past it had useless reports that did not affect us (on the content server), so we let it show a report but not block the Pull Request.

**Comment by pdehaan** [comment]
+1 to what @vladikoff said.
I love the tool, and definitely see it's value, but sometimes it was reporting potential vulnerable modules so deep in nested sub-sub-sub dependencies that it was hard to fix issues since it'd involve fixing the bug with a PR to the sub-sub-sub dependency, and then wait for all the upstreams to merge that change until you could eventually get a newer version with the issues fixed (and hope that the upstream modules would merge the PRs). In other cases, moving to a newer version of Hapi would be a massive undertaking.

It's also integrated with fxa-content-server (also through grunt-nsp) at https://travis-ci.org/mozilla/fxa-content-server/jobs/125837724#L806

See

```
Warning: (+) 13 vulnerabilities found
 Name        Installed   Patched     Path                                                                                                                              More Info                              
 moment      2.8.4       >=2.11.2    fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > convict@0.6.1 > moment@2.8.4                                        https://nodesecurity.io/advisories/55  
 hapi        8.4.0       >=11.1.4    fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > hapi@8.4.0                                                          https://nodesecurity.io/advisories/65  
 hapi        8.4.0       >=11.0.0    fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > hapi@8.4.0                                                          https://nodesecurity.io/advisories/45  
 hapi        8.4.0       >=11.1.3    fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > hapi@8.4.0                                                          https://nodesecurity.io/advisories/63  
 moment      2.9.0       >=2.11.2    fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > hapi@8.4.0 > joi@6.0.8 > moment@2.9.0                               https://nodesecurity.io/advisories/55  
 uglify-js   2.4.24      >=2.6.0     fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > uglify-js@2.4.24                                                    https://nodesecurity.io/advisories/48  
 uglify-js   2.4.24      >=2.6.0     fxa-content-server@0.60.0 > jsxgettext-recursive@0.0.5 > jsxgettext@0.4.10 > swig@1.3.2 > uglify-js@2.4.24                        https://nodesecurity.io/advisories/48  
 uglify-js   2.2.5       >=2.6.0     fxa-content-server@0.60.0 > i18n-abide@0.0.25 > jsxgettext@0.7.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5             https://nodesecurity.io/advisories/48  
 uglify-js   2.2.5       >=2.6.0     fxa-content-server@0.60.0 > jsxgettext-recursive@0.0.5 > jsxgettext@0.4.10 > jade@0.30.0 > transformers@2.0.1 > uglify-js@2.2.5   https://nodesecurity.io/advisories/48  
 uglify-js   2.2.5       >= 2.4.24   fxa-content-server@0.60.0 > i18n-abide@0.0.25 > jsxgettext@0.7.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5             https://nodesecurity.io/advisories/39  
 uglify-js   2.2.5       >= 2.4.24   fxa-content-server@0.60.0 > jsxgettext-recursive@0.0.5 > jsxgettext@0.4.10 > jade@0.30.0 > transformers@2.0.1 > uglify-js@2.2.5   https://nodesecurity.io/advisories/39  
 marked      0.3.5       None        fxa-content-server@0.60.0 > grunt-marked@0.1.3 > marked@0.3.5                                                                     https://nodesecurity.io/advisories/101 
 marked      0.3.5       None        fxa-content-server@0.60.0 > marked@0.3.5                                                                                          https://nodesecurity.io/advisories/101 

 Used --force, continuing.
Done, but with warnings.
```

I haven't played with **nsp** too much lately, but I'm pretty sure we can create a config file to ignore certain advisories (if we don't care about **marked** or **uglify-js**, for example).

With all that said, it's probably worth looking into updating some of these dependencies and see if we can remove some of these warnings.

Re: _"Does it have issues?"_,

I can't think of many personally, but I follow their repo and there have been recent complaints about their server's reliability (and reporting occasional HTTP 500s), and posting entire package.json contents (when it only needs 4-5 fields), and I think they may not currently be checking devDependies (but that may not be the case if you use npm-shrinkwrap.json file vs package.json checking).

**Comment by rfk** [comment]
I second what @pdehaan said - for some of our dependencies you can only get the proposed security fixes by doing a major version upgrade, and all the API churn that entails.  For one (I'm look at you, hapi) we have to actually upgrade to a newer version of node in order to get the latest release.  Under those circumstances, there's high incentive to look at the security warnings, confirm that they don't apply to our use of the package, and ignore them.  Which naturally builds warning fatigue and reduces the value of the tool.

**Comment by pdehaan** [comment]
Slightly derailing this train, but @rfk, maybe we should look into https://github.com/nodesecurity/nsp#exceptions and just excluding noise coming from the Hapi dependency, until we're ready to fully jump on the Node 4+ bandwagon (since it looks like hapi@11 only supports Node >=4.0.0 -- per https://github.com/hapijs/hapi/commit/1a6d4baa71fbb17d4e2e701dba145e4880677653).

**Comment by evilpacket** [comment]
Per path exceptions are coming, not sure when yet or how they will work but I can say that they are on the list :) - Also thank you for all the feedback in this thread. It's painful to read that something isn't performing as desired, but we can only use that to make things better. Thank you again.

**Comment by pdehaan** [comment]
I think the biggest takeaway from this conversation is https://github.com/nodesecurity/nsp/issues/98#issuecomment-214887703:

> @evilpacket: I wrote some really bad code way back when.

Because a) I totally ❤️ @evilpacket, b) taking things out of context is hilarious, and c) it totally reminds me of this:

![](http://izquotes.com/quotes-pictures/quote-i-used-to-do-drugs-i-still-do-but-i-used-to-too-mitch-hedberg-235984.jpg)

**Comment by rfk** [comment]
> maybe we should look into https://github.com/nodesecurity/nsp#exceptions and
> just excluding noise coming from the Hapi dependency

Cool, thanks for the tip!  I also second what @pdehaan said again - ❤️ @evilpacket 😄

**Comment by jvehent** [comment]
This is very useful feedback, so thanks of lot for sharing it.
Globally, regardless of the language, dependency management is ridiculously hard. I don't think we can realistically always be up to date with everything, but maybe focus on somewhat-high confidence indicator that an issue in a dependency impacts us.

>  there's high incentive to look at the security warnings, confirm that they don't apply to our use of the package, and ignore them. Which naturally builds warning fatigue and reduces the value of the tool.

What if we managed the output of nsp in github issues with a set of labels? If an issue is closed as `wontfix`, we make sure to never alert again for it, or later version of that package. The first run would take a bit of triaging, but that could reduce the noise from subsequent runs quite a bit. Thoughts?

**Comment by rfk** [comment]
I like where @pdehaan is going with https://github.com/mozilla/fxa-auth-server/pull/1241 - if we get a warning and can confirm that it doesn't affect use, we can open an explicit PR to discuss and add it to the list of exceptions.

**Comment by vladikoff** [comment]
We merged the PRs that introduced `exceptions`. Let us know if there are other questions or action items we can respond to here.

**Comment by jvehent** [comment]
Even with @pdehaan 's PR, this is still a manual process, correct?

What I'm wondering, at a high level, is if we can and should integrate these sort of checks with pull requests, or if they are better kept as external processes. I'd like to have something we can standardize on org-wise, and since FxA is already on top of things, I figured I'd start here :v:

**Comment by rfk** [comment]
>  is if we can and should integrate these sort of checks with pull requests,
> or if they are better kept as external processes.

Integrating the check into every pull-request doesn't seem like the right balance to me.  It's an easy integration point because we already have "automatically run some stuff on every pull-request" logic, but it has the downside of blocking unrelated changes from landing, even in the case of false positives.

A better approach would be something like what greenkeeper.io does, which I think is what @jvehent is driving at with this:

> What if we managed the output of nsp in github issues with a set of labels? 

Having a process that checks what's in master and files a new issue whenever a new security problem is identified, would be very valuable.  There's then two clear ways for us to resolve the issues that get files through this process:

* With a PR that updates the dependency to fix the issue
* With a PR that explicitly adds it to our ignore list

I think this would be a better balance than having NSP output on individual unrelated pull requests.  But if we decide to do something like that, we can probably track it in a separate issue.

**Comment by jvehent** [comment]
Thanks @rfk, that's good feedback. I'm experimenting with a couple solutions to do these checks out of bands. I'll see what works and what doesn't, and come back with a plan.

**Comment by evilpacket** [comment]
As an alternative we do have the ability to hook up to a github repo and flag vulnerabilities just like the ci server running it's tests. The benefit is that if we fail, it's independent of the tests (so it's not an all or nothing), you can see the details of the advisories and we also have point and click exception handling with an audit trail for handling false positives or acceptable risks. Let me know if you want to trial that out. It's pretty early but would love to get you trying it out and get feedback before it's commercially available.

**Comment by pdehaan** [comment]
@evilpacket Out of personal curiosity, I'd be interested in seeing the GitHub hooks in action (even if you just point me to somebody else's repo).

My initial concern would be that we've been seeing some nsp warnings in repos for a long time and probably won't resolve those anytime soon (either because they're dev dependencies, or they aren't fixed  upstream yet &mdash; for example [**marked**](https://nodesecurity.io/advisories/101)), so I wouldn't want to see nsp making the same comments on every commit from now until infinity.

**Comment by pdehaan** [comment]
@evilpacket Just to clarify, this was released and is https://nodesecurity.io/#pricing, correct?

**Comment by vladikoff** [comment]
@pdehaan nice!

**Comment by evilpacket** [comment]
Correct. open source repos are free, private beyond 1 are paid. 

It's just a process of signup and then, connect to github and then enable the various repositories. Default branch will be checked nightly and pull requests will get checked as submitted or updated. Advisories that you find to not apply to your project, false positives can be added via the web interface or a dot file as exceptions.

**Comment by evilpacket** [comment]
Please do.. it would be a great test. :)
