### ISSUE TITLE
ErrorNo 125 / Unkown Account on Login

### ISSUE THREAD

**Issue by Kornelis** [mozilla/fxa-auth-server#1248]
Hi,

i'm working on an App to Access my Firefox Bookmark via the StorageAPI.
But since a two to three week I always get the an Error for the Login Request using POST https://api.accounts.firefox.com/v1/account/login?keys=true with body:
{"email":"abc@def","authPW":"-stretchedPassword-"}

I haven't changed anything in my code but now I always get this Repsonse instead of the Key/Session Tokens:

"{"code":400,"errno":125,"error":"Bad Request","message":"Unknown account","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","email":"abc@def"} 

Is there anything that changed?
I traced the Firefox Login with Fiddler and saw they are sending an not documented ContentToken. Is this required? How is it generated?
Are there any other fields Required in the Header?

Thanks in Advance and kind Regards

Kornelis

**Comment by rfk** [comment]
Hi @Kornelis, thanks for reaching out and sorry for the breakage here.  This error is caused by an operational security mechanism that we put in place recently.  More info is available in this mailing-list thread:

  https://mail.mozilla.org/pipermail/sync-dev/2016-April/001345.html

We have a new deployment prepared which should lift this restriction and restore service, hopefully within the next week or two.
