### ISSUE TITLE
Add KeyFetchToken verification state support

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1287]
This is a follow up issue to add support for KeyFetchToken verification states. This ability was added to [fxa-auth-mysql-db](https://github.com/mozilla/fxa-auth-db-mysql/pull/138) and the auth-server needs to be updated to utilize these states.

**Comment by rfk** [comment]
Per discussion with @vbudhram and @shane-tomlinson, the idea here will be to:

* Make the /account/keys endpoint require a verified keyFetchToken.  If the keyFetchtoken is not verified then it returns the existing "account unverified" email, in the same way it would for an unverified account.

* Make the /account/login endpoint create an unverified keyFetchToken, using the safe tokenVerificationId as the corresponding sessionToken.  This will ensure that older android devices cannot progress past the call to `/account/keys` without verifying the session.

* Make the /password/change/start endpoint create a *verified* keyFetchToken.  This will ensure that the change-password flow does not have to do an email confirmation loop.

It's worth noting that because of the `/password/change/start` behaviour, there's no additional security provided here.  This change is only to help ensure existing clients go through the flow in the right order (which is why we can get away with the above-mentioned loophole for /password/change/start).

**Comment by shane-tomlinson** [comment]
> Make the /password/change/start endpoint create a verified keyFetchToken. This will ensure that the change-password flow does not have to do an email confirmation loop.

Can we pass an existing sessionToken to `/password/change/start` and the returned keyFetchToken is created with the same verification state as the sessionToken? The sessionToken is currently only passed to `/password/change/finish` so that the new `sessionToken` and `keyFetchToken` are created with the same verification state. On the surface, this seems to prevent `/password/change/start` from being used to gain keyFetchTokens with elevated powers and the rest of the flow should work as expected.

**Comment by rfk** [comment]
> Can we pass an existing sessionToken to /password/change/start and the returned keyFetchToken
>  is created with the same verification state as the sessionToken?

An unverified keyFetchToken is totally useless, since it's only accepted by a single endpoint, and that endpoint will insist on it being verified.  So ISTM this would put us back in the same situation as before, potentially requiring a confirmation loop in the middle of the change-password flow.

> The sessionToken is currently only passed to /password/change/finish so that the
> new sessionToken and keyFetchToken are created with the same verification state.

IIRC `/password/change/finish` does not generate a new `keyFetchToken`.

More broadly, I think we should figure out a way to authenticate `/password/change/start` and `/password/change/finish` directly with a `sessionToken` rather than requiring all these other transient tokens, but that's well outside the scope of this work...

**Comment by shane-tomlinson** [comment]
>  I think we should figure out a way to authenticate /password/change/start and /password/change/finish directly with a sessionToken rather than requiring all these other transient tokens, but that's well outside the scope of this work...

This statement make me feel like we are talking past each other and advocating for similar things to achieve the same goal - minimize complexity.

>  So ISTM this would put us back in the same situation as before, potentially requiring a confirmation loop in the middle of the change-password flow.

I have convinced myself that /password/change/start should be guarded by a verified sessionToken to begin with. An attacker that learns your password could use /password/change/start to get a verified keyFetchToken. For Sync, this isn't terrible because data is guarded by the verification status claim in the assertion. For Hello and any other future OAuth reliers that use keys and do not get an assertion, the security model is now broken. In addition, an attacker might not be able to get Sync data, but they can now change the user's password w/o any additional security measures. This will require the user to reset their password, which in turn causes the user's existing Sync data to be jettisoned.

The second thought is, why does the password change flow need to call /account/keys at all? Why not just return keys as part of /password/change/start if ?keys=true? The extra steps require creating/storing a keyFetchToken, then calling a separate endpoint which must then verify the just returned keyFetchToken. Seems like a lot of extra work to store/check tokens to me, why do it if we don't need to? A similar question goes for the password reset flow; why not just return keys as part of /account/reset?

> IIRC /password/change/finish does not generate a new keyFetchToken

[Yes, yes it does](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/password.js#L159), the new sessionToken and keyFetchToken are passed to the browser w/o the need to call `/account/login`, which would trigger the signin confirmation flow.

**Comment by rfk** [comment]
> Yes, yes it does,

Ah yes, sorry, I forgot we had added that recently.

> I have convinced myself that /password/change/start should be guarded
> by a verified sessionToken to begin with.

I agree that we need to get to such a point.  Or more precisely, I agree that in the long term all access to encryption keys should require a verified token.  (Which in the long term, might be 2FA rather than an email confirmation loop).

> The second thought is, why does the password change flow need to call /account/keys at all?

Indeed.  I think it's only because that's the One True Way to get keys in our API at the moment, and it gives us a point at which to centralize the rules around key access control.  But we could certainly work towards an API that just returns the keys directly.

> A similar question goes for the password reset flow; why not just return keys as part of /account/reset?

For this one, we need to return a keyFetchToken because that's what the browser expects to receive, if we wanted to change that we'd probably have to make some significant changes to the browser.

Zooming out, there are two questions afoot that I think are getting conflated in this bug, one narrow and one broad:

1. What do we need to do in order to enable the sign-in confirmation feature on mobile devices?
2. How do we add a mechanism for protecting access to the encryption keys in general?

ISTM that we have a solid plan for (1) that is a first step on the path to (2), and we don't need to block it on solving (2) in its entirety.
