### ISSUE TITLE
Request blocked

### ISSUE THREAD

**Issue by paha77** [mozilla/fxa-auth-server#1308]
I get the following response when I'm synchronizing history:

```
{ code: 400,
  errno: 125,
  error: 'Request blocked',
  message: 'The request was blocked for security reasons',
  info: 'https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format' }
```

In: node_modules/fx-sync/node_modules/fxa-js-client/node_modules/p-promise/p.js:146

Do you have any idea why?  

Thank you.

**Comment by rfk** [comment]
Hi @paha77.  This error code is returned when we block a request because it looks suspicious, e.g. because it may be coming from an IP with an unusually high rate of login attempts, or it may appear "unusual" in ways that are similar to known attack attempts.

We're currently operating at a heightened level of security measures, so I'd say that we've unfortunately caught our request in this filter as a false positive.  Things should return to normal in a few days.

**Comment by rfk** [comment]
@paha77 out of curiosity, what are you synchronizing with?  From your use of `fxa-sync` module it looks like a custom integration of some sort?

**Comment by paha77** [comment]
@rfk Thank you for the answer.  I've tried it from another (dynamic) IP but got the same error code, while the Firefox browsers with this account synchronize normally.  Anyway, it's just an experimental project of me, I've created a simple Node application that queries my browsing history in the last 24 hours and saves it into a database.

**Comment by vladikoff** [comment]
@rfk to triage...

**Comment by rfk** [comment]
I don't think there's anything actionable here, we just need to wait until we can lower the thresholds to normal background rate.  So let's close out the issue.
