### ISSUE TITLE
Longer term solution for multiple emails on login

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1325]
This is a follow up issue from https://github.com/mozilla/fxa-auth-server/pull/1317.

Currently, when signing into FxA with an _unverified_ user and utilizing the content-server, two emails will be sent, `Verify your Firefox Account` and `New sign-in to Firefox`. Below are a summary of some of the issues that have already been touched on, but not yet resolved.

* Can we add location information to `Verify your Firefox Account` to have it contain the same information as `New sign-in to Firefox`?
* Should the content-server automatically resend email to verify account on login and the ramifications of changing this.
* User experience and expectations?

cc @shane-tomlinson @ryanfeeley @rfk

**Comment by shane-tomlinson** [comment]
The most important thing to fix is how both sessions in this scenario become verified if the user opens the verification link sent when the 2nd device signs in. If we fix that first and provide the security, we can iterate on the emails in a more leisurely manner.

**Comment by vladikoff** [comment]
from mtg: might move this out of the milestone into its own thing..

**Comment by rfk** [comment]
> The most important thing to fix is how both sessions in this scenario become verified
> if the user opens the verification link sent when the 2nd device signs in.

AFAICT this is fixed - we always use the tokenVerificationId of the sessionToken that is calling `/recovery_email/resend_code`, so we'll never accidentally verify both sessions.

> Should the content-server automatically resend email to
> verify account on login and the ramifications of changing this.

I understand it will be difficult to change this in a backwards-compatible way, but I really dislike having the logic for which-emails-are-sent-when spread out between auth-server and content-server.  I think we should try to consolidate this logic into the auth-server.

How awful would it be to do something like the following?

* Have content-server send its version number in all requests to the auth-server, and have the auth-server send its version number in all responses.
* Have auth-server take responsibility for sending the email if content-server version is > X, and have content-sever maintain responsibility for sending it if auth-server version is < Y.
* After a couple of trains, deprecate that logic so that the auth-server is always responsible for automated sending of emails.

My gut says "tolerably awful"...

> User experience and expectations?

I think the logic we have baked into the `/recovery_email/resend_code` endpoint right now is fine:

```
        if (sessionToken.emailVerified && sessionToken.tokenVerified) {
          return reply({})
        }

        if (sessionToken.tokenVerificationId) {
          code = sessionToken.tokenVerificationId
        } else {
          code = sessionToken.emailCode
        }

        if (!sessionToken.emailVerified) {
          func = mailer.sendVerifyCode
        } else {
          func = mailer.sendVerifyLoginEmail
        }
```

We send the verify-your-account email if the account is unverified, and the verify-your-login email otherwise.  We use the code form the current sessionToken if it has one, and the code from the account otherwise.

If we can stop the content-server from triggering email sends of its own volition, and have the /account/login endpoint follow the same logic as above, then I think we'll be in a sensible-enough state to close out this issue.

@vbudhram @shane-tomlinson thoughts?

**Comment by rfk** [comment]
>  I really dislike having the logic for which-emails-are-sent-when
> spread out between auth-server and content-server. 

As a concrete example of why, I feel like the current setup is going to make things more complicated for us when we come to implement geo-profiling or other mechanisms which may further influence what emails the auth-server chooses to send.  Being able to see all the rules in a single location, will make working through such scenarios much simpler.

**Comment by shane-tomlinson** [comment]
> * Have content-server send its version number in all requests to the auth-server, and have the auth-server send its version number in all responses.
> * Have auth-server take responsibility for sending the email if content-server version is > X, and have content-sever maintain responsibility for sending it if auth-server version is < Y.
> * After a couple of trains, deprecate that logic so that the auth-server is always responsible for automated sending of emails.

> My gut says "tolerably awful"... 

I think versioning is useful in certain situations, I'm trying to figure out if this is one of them. Versioning is an indirect way of doing a capabilities handshake.

We have another way of handling handshakes like this - using query parameters and options send in the request, e.g. passing `sesionToken: true` to `/account/unlock/verify_code` means "gimme a new session token." This was added because `/account/unlock/verify_code` did not originally support creating new sessionTokens and we only wanted sessionTokens to be created for clients that could support it.

I can imagine the `/account/login` endpoint could accept a new option or query parameter `sendMailIfUnverified: true` (or some other better name) if the content server wants to delegate that power to the auth server. The auth server would respond with `verified: false, emailSent: true`. The content server would see `emailSent: true` and not send the email. Legacy clients would never send the `sendMailIfUnverified: true` option, and the auth server would not send the emails for these clients. After a train or two, the content server could stop checking for `emailSent: true`

Advantages:

* No indirection with version=>capabilities "What's supported in this version?"
* Capabilities handshake logic to request sending of the email is localized.

Disadvantages:

* The content server will have to send the `sendMailIfUnverified: true` until all legacy clients go away or we determine there are sufficiently few and can send duplicate emails, or we come up with some other scheme to prevent duplicates from being sent.

> * After a couple of trains, deprecate that logic so that the auth-server is always responsible for automated sending of emails.

Considering legacy clients, this may be very far in the future. How does Fx OS, Samsung and old Fennec deal with unverified accounts on login? Do they trigger `/recovery_email/resend_code` themselves? If so, we have to keep some gating logic around to avoid sending duplicate emails. Using versioning, we could say if no version number is sent, we assume it's legacy and send the emails. Another alternative is to add some foo to the `/recovery_email/resend_code` endpoint to say `if an email has been sent to this address in the last 2 seconds, don't send another`.

**Comment by vbudhram** [comment]
> The most important thing to fix is how both sessions in this scenario become verified
if the user opens the verification link sent when the 2nd device signs in

You are correct @rfk, this is fixed.

Both of the solutions you guys outlined seem reasonable to me. Since they both follow a similar pattern, version number vs query params, I am not torn either way. We have done the query param dance for doing similar things in the content server and auth server, so I don't think it would be to bad.

> Have content-server send its version number in all requests to the auth-server, and have the auth-server send its version number in all responses.

I don't see a reason for us not to do this. Seems like a useful thing to add in general?

> How does Fx OS, Samsung and old Fennec deal with unverified accounts on login?

I am guessing that these clients don't use content-server or js-client, but interface directly with api?

**Comment by rfk** [comment]
> How does Fx OS, Samsung and old Fennec deal with unverified accounts on login?
> Do they trigger /recovery_email/resend_code themselves?

I don't believe any other platforms call this endpoint, but you're right, we should check.  The one I think would be most likely to call it is Firefox OS.

**Comment by rfk** [comment]
FWIW I can't see any code-paths in mozilla-central, B2G or firefox-ios repos that would trigger an automated resend.

> Legacy clients would never send the sendMailIfUnverified: true option, and the auth server
> would not send the emails for these clients.

Hrm.  If those clients are *not* explicitly triggering a resend of the verification email, what experience are they getting right now?  I suspect they're not getting either of the "verify your account" or "confirm your signin" emails.

**Comment by shane-tomlinson** [comment]
> Hrm. If those clients are not explicitly triggering a resend of the verification email, what experience are they getting right now? I suspect they're not getting either of the "verify your account" or "confirm your signin" emails.

This is an excellent point that I had not considered. I blindly assumed all clients would "do what the content server does". If that's not the case then we should fix this with a quickness.

**Comment by rfk** [comment]
From meeting, next action is on @shane-tomlinson to confirm behaviour of legacy clients, since he happens to have one lying around.

**Comment by shane-tomlinson** [comment]
> From meeting, next action is on @shane-tomlinson to confirm behaviour of legacy clients, since he happens to have one lying around.

Ugh, my device is at home.

**Comment by shane-tomlinson** [comment]
> From meeting, next action is on @shane-tomlinson to confirm behaviour of legacy clients, since he happens to have one lying around.

FxOS does *not* send the email. The UI says "We will send an email to...", but no email arrives. The only way to have the email resent is to click on the "resend" link. 

@rfk - you mentioned having the emulator foo to test old Fennec and Samsung S browser.

**Comment by rfk** [comment]
On SBrowser, I get the same experience - it shows the "verify account" screen with "A verification link has been sent to...", but the email is not re-sent.

**Comment by rfk** [comment]
So I think we're going to need to move forward on the plan from https://github.com/mozilla/fxa-auth-server/issues/1325#issuecomment-238194755 or on something similar, so that we can make the auth-server responsible for sending the emails in all cases.

**Comment by vladikoff** [comment]
status: needs more PRs., needs breakout issues, cc @vbudhram

**Comment by vbudhram** [comment]
Closing this bug since breakout issues have been made.
