### ISSUE TITLE
Clicking `Confirm sign-in` email button twice displays error

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1367]
STR: 

1) Signup and verify account
2) Login into Sync with account that requires sign-in verification
3) Click `Confirm sign-in` button in email, page opens to verified success view
4) Click `Confirm sign-in` button again

Expected:
page opens to verified success view

Actual:
page opens damage verification link view
<img width="466" alt="screen shot 2016-07-26 at 12 13 32 pm" src="https://cloud.githubusercontent.com/assets/1295288/17145984/9c8bf036-532a-11e6-83ea-2eca71f4714a.png">

**Comment by vbudhram** [comment]
It appears that when the user first clicks the email link, the account/session gets verified and removed from unverified tokens table. Clicking the link again, [throws an error](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L1133) because code is not in unverified tokens table nor is it an account verification token.

**Comment by rfk** [comment]
This is the intended implementation behaviour, but it's not the intended user-facing behaviour :-(

Our whole notion of "unverified tokens" depends on deleting the row from the table once it's verified, so we can't do the simple thing of just keeping the verification code around.

We could change the way the token verification table works, so that rather than than storing `(tokenId, uid, code)` and deleting rows to indicate verification, we store `(tokenid, uid, code, status)` and flip the `status` to true when you verify the token.  That's non-trivial database surgery, but might have some other benefits as well.

Or, we could incorporate a HMAC into the verification code.  This would let us inspect the code itself and determine that yes, this was a valid code at some point in the past, even though it's no longer present in the database.  This may turn out to be the simpler path forward for resolving this specific issue, if we don't want to do any database surgery.

Leaving the behaviour as-is, doesn't seem like a good option to me.

**Comment by vbudhram** [comment]
I like the HMAC idea, but I am not sure of all the changes/pieces involved with implementing it. I wonder if it would be suffice to give the user a more vague error, something along the lines of `Invalid or Damaged Verification`. This doesn't solve the problem, but does give the user an better idea of what could have happened.

**Comment by shane-tomlinson** [comment]
Re-opening as https://github.com/mozilla/fxa-content-server/issues/4009. Closing here.
