### ISSUE TITLE
request_helpers.shouldEnableSigninConfirmation returns true for email matches even if not requesting keys

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1374]
Ref https://github.com/mozilla/fxa-content-server/issues/3988

The content server's [sign_in_cached functional tests](https://github.com/mozilla/fxa-content-server/blob/c1b42bcc66b308aa26fc59e64030893b19ae17a7/tests/functional/sign_in_cached.js#L243) are failing because the email used to sign in begins with a `sync` prefix. [request_helpers.shouldEnableSigninConfirmation]() does not check whether keys are requested when making its choice. The function sees that the email matches the `sync` prefix and returns `true`.

`shouldEnableSigninConfirmation` should only return true if keys are requested.

**Comment by shane-tomlinson** [comment]
We didn't notice this oversite before #1361 because we previously checked the `context` first. If the `context` didn't match the list, then we returned `false`.

**Comment by shane-tomlinson** [comment]
> shouldEnableSigninConfirmation should only return true if keys are requested.

An alternative is for the content server to change the email prefix for these tests. I'll take that approach for now and leave this open for discussion.

**Comment by shane-tomlinson** [comment]
> An alternative is for the content server to change the email prefix for these tests.

That won't work because some of the tests test a user that signs up/in for Sync, and then signs in for another non-key requesting relier.

**Comment by rfk** [comment]
I'm re-opening this because #1375 seems to have had unintended consequences.

> shouldEnableSigninConfirmation should only return true if keys are requested.

I agree that we shouldn't *send the email* when keys are not requested, but I don't think we should disable the feature entirely.  Rather, keyless sessions should be created in the unverified state and stay there indefinitely.

It's not obvious from the bug, what the failing behaviour is from content-server's perspective - did we send emails when it wasn't expecting us to?

**Comment by rfk** [comment]
OK, what I *think* is going on here, is that we're incorrect responding to keyless login sessions with `verificationReason: 'login'`, despite the fact that we don't send a signin confirmation email.

**Comment by rfk** [comment]
More specifically, I think we're hitting a very funky corner-case that goes like this:

1. User signs in without requesting keys.  This creates an unverified sessionToken, but since it's not requesting keys, the server does not return a `{ verificationReason: 'login', verificationMethod: 'email' }` challenge response, and the login flow proceeds normally.
2. The content-server stashes this unverified sessionToken in localStorage for later use.
3. The user comes back to do another login, also without requesting keys.  The content-server sees it has a cached sessionToken and decides to use it.
4. The content-server calls `/recovery_email/status` to check on the status of its cached sessionToken.  Since the sessionToken is unverified, this endpoint returns `{ emailVerified: true, sessionVerified: false }`, which the code at [1] converts into a `{ verificationReason: 'login', verificationMethod: 'email' }` challenge response.
5. The content-server interprets this to mean that it should show the confirm-signin screen, even though the user is not doing anything that would require a verified session.

@shane-tomlinson does this fit with what you were seeing?

If so, then I want to propose the following as a path forward:

1. Ship #1375 in train-66, but with some additional commentary about it being a temporary work-around.

2. Finalize the additional test-cases in #1376 so that we know what the final security boundary of this thing is supposed to look like.

3. Figure out how we're going to reconcile the two for train-67 and beyond.  I suspect we may have to add some additional smarts to content-server to avoid (5) above, but I'm wary of piling on additional branching logic to an already complicated set of flows...

[1] https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/fxa-client.js#L602

**Comment by rfk** [comment]
> Ship #1375 in train-66, but with some additional commentary about it being a temporary work-around.

Like this:  https://github.com/mozilla/fxa-auth-server/pull/1377

**Comment by shane-tomlinson** [comment]
> More specifically, I think we're hitting a very funky corner-case that goes like this:

The problem is even simpler than that. No need to do a second login. 

Simple pre #1375 STRs

1. Sign up with a sync.*@restmail.net email address, verify.
1. Sign in, without requesting keys.
1. Signin confirmation screen is displayed.

`/account/login` returns:

<img width="506" alt="screen shot 2016-07-29 at 09 16 06" src="https://cloud.githubusercontent.com/assets/848085/17242061/14233a7a-556d-11e6-96c6-f0db7a09a218.png">

The content server sees `verified: true` and ships the user to the `/settings` page.

The `/settings` page sees the account's sessionToken and calls `/recovery_email/status` with the token to ensure the session is still valid. 

`/recovery_email/status` returns:

<img width="404" alt="screen shot 2016-07-29 at 09 17 33" src="https://cloud.githubusercontent.com/assets/848085/17242102/4db53aea-556d-11e6-9a35-5ef93ed809ed.png">

From an external viewer, `/account/login` behaves correctly, `/recovery_email/status` is...tricky, possibly incorrect. The front end doesn't actually care whether the session can be used for Sync, it just wants to know what its next steps should be. This means knowing whether the session is valid, if so, whether the user must view a confirmation screen, and if so, which one. Returning `emailVerified` and `sessionVerified` instead of `verificationReason` and `verificationMethod` I thought might shoot us in the foot eventually. Lack of `verificationReason` means we have to convert `emailVerified` and `sessionVerified` to one of `signup` or `login`. Lack of `verificationMethod` will be problematic for 2FA if the user must use some non-email method for verifying.

My initial impression is that a fix should be auth-server only. Having the content server branch based on whether keys are requested spreads logic that should be centralized and is going to limit flexibility when it comes time to implement 2FA.

It seems to me we have conflated two questions in a single function `shouldEnableSigninConfirmation`.

1. Should the user see the signin confirmation screen and the corresponding email be sent?
1. Can this session be used for Sync, i.e., is this session "verified"?

These two questions are subtly different. If the answer to 1 is "no", the answer to 2 is not automatically "no." With the coming geo/ip based decision making, these two will be largely decoupled. A session may be created in the verified state w/o the user seeing signin confirmation. In reverse, if the answer to 2 is "yes", 1 doesn't have to be "yes".

**Comment by rfk** [comment]
This was fixed in train-67 by adding the "mustVerify" flag to tokens
