### ISSUE TITLE
Add a flowEvent for account.email_bounced

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1425]
Need it for sign up (and sign in?)
Ref: https://github.com/mozilla/fxa-auth-server/blob/master/lib/bounces.js#L70

**Comment by philbooth** [comment]
Related to / a partial dupe of mozilla/fxa-content-server#4040.

**Comment by seanmonstar** [comment]
Just took a preliminary look around, we need some way to link this message back up to a flow. There are some hacky things we could try to do, but the cleanest to me seems like we should just start adding a `X-Flow-Id` header to the messages, and then we can grab it from the SES message and just log with that ID.

**Comment by rfk** [comment]
> adding a X-Flow-Id header to the messages

I like this.  I was thinking we'd have to grade the `X-Verify-Code` or whatever header, and then look in memcached to tie that code back to a flowid.  Directly including a flow-id header seems much nicer!

**Comment by vladikoff** [comment]
Blocked on getting header logs from production

**Comment by rfk** [comment]
I have vague recollections of a bugzilla bug tracking that work in production, anyone happen to have a link if so?

**Comment by vladikoff** [comment]
Need to figure out what info we needed to log.

**Comment by vladikoff** [comment]
need to talk to whd about bouncer.js logs...

**Comment by vbudhram** [comment]
Spoke with whd and he said that import scripts should process new flowEvents, however, I was not able to see them in redash. Going to wait a day or so to verify this since train with updates was recently shipped.

**Comment by philbooth** [comment]
> I was not able to see them in redash.

Hmm, yeah, not sure if I'm looking in the right place but I also can't see them in Kibana:

https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Auth%20Bouncer%20Logs

**Comment by vbudhram** [comment]
@philbooth Followed up with @whd and he said that the events were not being imported because they are not being logged correctly in bouncer process.

Incorrectly logged [here](https://github.com/mozilla/fxa-auth-server/blob/05307ea5e7ee735aa5cafdcfd2971afbc7a1af24/lib/bounces.js#L130).

How it should be logged [here](https://github.com/mozilla/fxa-auth-server/blob/05307ea5e7ee735aa5cafdcfd2971afbc7a1af24/lib/bounces.js#L13).

My question is if I were to update it to match this format which `op` value should I use? Auth server uses `log.flowEvent`, but those are only on [errors](https://github.com/mozilla/fxa-auth-server/blob/05307ea5e7ee735aa5cafdcfd2971afbc7a1af24/lib/log.js#L212).

New bouncer log statement would look like this:
```javascript
log.info({ op: 'log.flowEvent', event: eventName, time: currentTime, flow_id: flow_id, flow_time: elapsedTime })
```

**Comment by philbooth** [comment]
> Incorrectly logged [here](https://github.com/mozilla/fxa-auth-server/blob/05307ea5e7ee735aa5cafdcfd2971afbc7a1af24/lib/bounces.js#L130).
>
> How it should be logged [here](https://github.com/mozilla/fxa-auth-server/blob/05307ea5e7ee735aa5cafdcfd2971afbc7a1af24/lib/bounces.js#L13).

I might be wrong, but I'm not convinced the format is the problem here. If I look at the bouncer logs in Kibana and query for those two log messages you link to, I can only see `accountDeleted`. I don't see any `flowEvent`:

<img width="824" alt="Screenshot of Kibana dashboard showing a distinct lack of bouncer flow events" src="https://cloud.githubusercontent.com/assets/64367/22061210/d5631bde-dd6b-11e6-8d98-25912c28c06f.png" />

Do we know if your flow events are actually being logged at all?

**Comment by philbooth** [comment]
For instance, do we know for certain whether [this condition](https://github.com/mozilla/fxa-auth-server/blob/a8f8c4a2f128697c3a02dc5fd4ce4c1a8e6faece/lib/bounces.js#L118) is being entered in production? Are we definitely getting the value we expect for, say, `X-Flow-Begin-Time`?

Maybe it's worth adding an `else` to that condition, logging an error so we can see whether it fails? Something like:

```js
} else {
  log.error({ op: 'handleBounce.flowEvent', flowId, flowBeginTime, currentTime })
}
```

**Comment by vladikoff** [comment]
@vbudhram can you add the final link to the dashboard?

**Comment by vbudhram** [comment]
https://sql.telemetry.mozilla.org/queries/2323#4293
