### ISSUE TITLE
Should we filter profanities in our unblock code generation?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1497]
The note in this wikipedia article got me thinking:

  https://en.wikipedia.org/wiki/Base32#Crockford.27s_Base32
  "It also excludes the letter U to reduce the likelihood of accidental obscenity."

Should we expend some modest effort in avoiding profanities in our signin unblock codes?  Unlike other randomly-generated codes in our system, the user actually has to read and type these out, so any unfortunate letter groupings are bound to get noticed.

I'm sure the long tail is a losing battle, especially given our multi-lingual audience.  But perhaps we can avoid the most obvious problematic letter combinations with minimal effort?

/cc @shane-tomlinson @seanmonstar

**Comment by seanmonstar** [comment]
I suppose this and the suggestion to use Base32 would both improve user experience some.

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Reminds me of: http://www.adweek.com/adfreak/coca-cola-apologizes-vitaminwater-bottle-cap-read-you-retard-152548

Sounds reasonable, though pretty unlikely in a randomly generated string. I wonder if we use an unambigous character set (that removes characters like 1, I and l) if it will help.

**Comment by rfk** [comment]
Indeed.  Or removing all the vowels and figuring can get away with accidental l33tsp34k profanity.  I (unfortunately) don't know how to curse in all our l10n-supported languages, but they all seem likely to need vowels :-P

Anyways, I don't think we need to block on this, and the good news is we can tweak it at any time with an auth-server update.

**Comment by philbooth** [comment]
From the meeting, me and @jrgm both think we should just use numbers and make it a bit longer if we need more entropy.

**Comment by rfk** [comment]
re: entropy, since these codes bypass signin-confirmation, the minimum entropy requirement should be the same as email verification codes, which are currently 16 bytes.

**Comment by rfk** [comment]
(Alternately, we should have an explicit conversation about why these codes can be lower entropy than the email verification codes)

**Comment by philbooth** [comment]
...or hex, if that inches us a little closer to the entropy:length happy medium.

**Comment by shane-tomlinson** [comment]
I'm not yet tied to any particular strategy, but I'd like to question the assumptions/requirements in the below statement

> re: entropy, since these codes bypass signin-confirmation, the minimum entropy requirement should be the same as email verification codes, which are currently 16 bytes.

AFAICT, we used 16 bytes for signin confirmation because that's what other codes used and we wanted to be API compatible with existing endpoints. Keep in mind signin confirmation links *never expire* whereas unblock codes have a lifetime of 1 hour. We could drastically cut the unblock code lifetime if we find some acceptable X% of emails arrive in Y minutes. My feeling is that if we rate limit code sending and code verifying properly, shorter codes with a short lifetime should be acceptable.

Most 2FA methods balance security and ease of use by using short codes that are only valid for some small number of seconds or minutes. Since we have a (sometimes) slow email send, we have to work with that constraint. Still it seems like we should be able to help the majority of our users without being too difficult to use.

> ...or hex, if that inches us a little closer to the entropy:length happy medium.

If we are in fact tied to 16 hex characters of entropy, hex would require the user to type 16 characters, which is an awful lot on a mobile device.

**Comment by rfk** [comment]
@shane-tomlinson I find your reasoning above compelling, as long as we're above industry-standard entropy levels for for 2FA codes then it's fine by me.

**Comment by seanmonstar** [comment]
So, I've seen suggestions and questions, but after re-reading the thread, I'm not certain if there is a definitive action yet. Did we really want to try this in some way? If yes, I can change to a "base32 removing `I`, `O`, `L` and `U`" (or Crockford's Base32). If not, I'll toss this in the backlog.

**Comment by rfk** [comment]
I propose we switch to crockford's base32 to both reduce confusion between similar characters, and avoid the most obvious english-language obscenities.  Going any further sounds like it would quickly become a losing battle.
