### ISSUE TITLE
seeing a lot of '"op":"metricsContext.gather","err":"Error: Missing token"' in stage. Expected?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1595]
Just filing this to get an opinion on whether this is expected. Seeing a lot of '"op":"metricsContext.gather","err":"Error: Missing token"' in stage. 

@rfk, @philbooth ?

**Comment by philbooth** [comment]
Yeah, totally expected, sorry.

At the risk of replying with too much detail, that error occurs when we try to delete the metrics context data before it has been stashed. This was already the case when the flow complete signal was `account.login` or `account.created`, but that has been widened now to include `account.reset` with the landing of #1584 and mozilla/fxa-content-server#4489 for train 76.

Perhaps it shouldn't be an error? It's possible for circumstances to arise where that state would be a genuine error, but they are vastly outnumbered by these legitimate cases.

Or I could try to rework the code to be smarter about when we emit it, and only log the genuine error cases. Actually, that does seem like the correct thing to do now I say it out loud, I'm looking into it now.

**Comment by philbooth** [comment]
> Yeah, totally expected...

Actually, I take that back. I forgot that [we swallow these errors when they happen in `metricsContext.clear`](https://github.com/mozilla/fxa-auth-server/blob/master/lib/metrics/context.js#L162-L169), so the ones in the logs on stage must be coming from `metricsContext.gather` instead. I'm still trying to figure out whether we expect to see a jump in those or not.

**Comment by philbooth** [comment]
Okay, yes, a jump is expected in train 75. It happens because, [now that `account.reset` is a flow event](https://github.com/mozilla/fxa-auth-server/pull/1584/files#diff-efdf7f1b383568bc3d7e94eb208431bcL31) we have more attempts to speculatively gather metrics context data than there were before.

However, we can definitely silence these errors to eliminate noise in the future. I'll open a PR against this issue.
