### ISSUE TITLE
Remove datadog / statsd metrics reporting

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1611]
* remove the statsd stuff from the server
* check to make sure push events are logged into Kibana and we have a push dashboard to keep an eye on Auth Server + Push Server health...

**Comment by sunakshi96** [comment]
Hii 
Could you please explain this bug in detail?

**Comment by seanmonstar** [comment]
Hm, that is it 'good-first-bug' is interesting. The first part would be on a the simpler side, which is just removing the statsd stuff. We have methods in our `lib/log.js` file that push things to statsd. I imagine this bug wants that stuff removed.

The second part, verifying in Kibana, would require a Mozilla email address, so I wouldn't expect you need to worry about that.

**Comment by vladikoff** [comment]
We need to remove code that was added in https://github.com/mozilla/fxa-auth-server/commit/63842b0016138791fcd7f458cf544e5cd183fac9 (since then there were more changes and usages added)

**Comment by sunakshi96** [comment]
> Hm, that is it 'good-first-bug' is interesting. The first part would be on a the simpler side, which is just removing the statsd stuff. We have methods in our lib/log.js file that push things to statsd. I imagine this bug wants that stuff removed.

Okay , what I understand is that all the data that is channelized to statsd stuff has to be removed.

> The second part, verifying in Kibana, would require a Mozilla email address, so I wouldn't expect you need to worry about that.

If I am correct, this part does nt require any changes in the code because that is already done in step 1?

> We need to remove code that was added in 63842b0 (since then there were more changes and usages added)

There are 13 additions done in log.js file, we need to remove that only? right?




>

**Comment by seanmonstar** [comment]
@sunakshi96 I believe the code in that commit is what we want to remove, along with any calls to `log.increment` that have also appeared.

**Comment by rfk** [comment]
Hi @sunakshi96, thanks for diving into this issue!  The dev team discussed this a little more today, and decided that it would be useful to keep some of the datadog / statsd metrics reporting in this server, while removing many of it uses.

Of the code that was added in https://github.com/mozilla/fxa-auth-server/commit/63842b0016138791fcd7f458cf544e5cd183fac9, can we please keep the changes to the following files:

* `./config/index.js` 
* `./lib/metrics/statsd.js`
* `lib/log.js`
* `package.json`
* `test/local/statsd_tests.js`
* `.env.dev`

But let's remove:

* the calls to `log.increment` in `lib/routes/account.js`
* any other calls to `log.increment`, `log.timing`, or `log.histogram` in other files under `./lib/`
* the call to `statsd.write` in the `Lug.prototype.activityEvent` function here: https://github.com/mozilla/fxa-auth-server/commit/63842b0016138791fcd7f458cf544e5cd183fac9#diff-bfaf7f17089346f4cf68d867a9bed34fR81

This will remove all the existing calls to statsd in the server, which is good because we're not really using those metrics for anything.  But it will leave the infrastructure in place for us to carefully add some new ones in the future.

**Comment by sunakshi96** [comment]
Okay let us filter the code then!

**Comment by sunakshi96** [comment]
All the required changes were done in the files. However the travis test doesnt pass. There is something which is not covered. Can somebody guide what could be the possible solution to this?

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
Hi @sunakshi96, please let me know whether you still plan to work on this, otherwise I'll go ahead and pick up your PR, fix up the tests and get it merged.  Thanks!

**Comment by sunakshi96** [comment]
@rfk 
I realize that this issue has taken a lot of time from my side. I am simply **not** planning to work on this.
Thank you for giving time to resolve.

**Comment by rfk** [comment]
No worries @sunakshi96, thanks for letting me know and for your contributions here already!
