### ISSUE TITLE
move checkNumberOfActiveSessions after `reply` to avoid extra db request before response

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1625]
from irc

```
[11:51:26]  <pb>	https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L736-L754
[11:54:32]  <vladikoff>	pb, hm related to that, if checkNumberOfActiveSessions doesn't do anything but logging we can probably move it after `reply` to optimize the login process
[11:55:00]  <pb>	vladikoff: that's true
```

We should check the load tests and see if the optimization is worth it

**Comment by vladikoff** [comment]
New location of the function https://github.com/mozilla/fxa-auth-server/blob/c805f9c334b99c1162f3389fc5c98d0b5ad602e5/lib/routes/utils/signin.js#L208

**Comment by philbooth** [comment]
Hmm, @vladikoff... since this code got refactored into that `sendSigninNotifications` util function, it feels like it lives in the right place from a semantic standpoint now. Remember it's called from two different routes now.

So even if moving it after the `reply` is worthwhile from a performance standpoint (which we haven't actually measured yet), I'm not sure it would make sense to move it. And it probably isn't as simple as keeping it where it is but running it in the next tick of the event loop either, because plenty of other async stuff goes on after this so the next tick would kick in and it would still run before the response.

I'm wondering if just closing this issue might actually be best. What do you think?

**Comment by vladikoff** [comment]
@philbooth should we just remove this `return` here https://github.com/mozilla/fxa-auth-server/blob/c805f9c334b99c1162f3389fc5c98d0b5ad602e5/lib/routes/utils/signin.js#L228 ?

and not block on that call, it doesn't return anything

**Comment by rfk** [comment]
>  it doesn't return anything

It has the side-effect of populating the `sessions` variable, which is used in `emitLoginEvent`.  I agree that's super unclear from the code as currently structured though, it may be worth refactoring to make things clearer.

**Comment by vladikoff** [comment]
🗡
