### ISSUE TITLE
Problem navigating to the "Manage Account" Page on full stack self hosting

### ISSUE THREAD

**Issue by level20peon** [mozilla/fxa-auth-server#1718]
When navigating to the "Manage Account" Page, I get an "invalidAssertion" error with "msg":"invalid email" back from the oauth server.

After digging into this, it turns out that the response from a POST to the auth server (https://fxa-auth.my.domain.tld/v1/certificate/sign?service=content-server) returns a key of some sorts, which is POSTed to the oauth server in the next step. This key seems to somehow include the "invalid" email address.

Now the interesting part is that this email address looks like this:
58C0CAF2633E435E99FBC7F5E1854635@fxa-auth.my.domain.tld

The actual email I registered looks like this:
abc@my.domain.tld

The 58C0... is the binary value (uid) in the accounts table of the fxa-auth-server mysql database for that abc@... email address.

So the question is: why does it use that uid instead of the correct email address, so that the assertion won't fail?

**Comment by seanmonstar** [comment]
@level20peon The auth and oauth servers don't talk about you by your email address, but by a permanent UID. This was in preparation for eventually allowing a user to have multiple email addresses assocaited with their account, or to change their email.

So, the oauth server takes a browserid assertion, which requires an email subject. Since we want to talk about an FxA UID, it's in the form of `<uid>@<fxa.domain>`. **The reason for the error** is that the `<fxa.domain>` part must match what the oauth-server expects in its config. You'd want to update the config for your oauth server, specifically this property: https://github.com/mozilla/fxa-oauth-server/blob/v1.81.0/lib/config.js#L33

**Comment by level20peon** [comment]
ok, thank you - that fixed it.

I was already on track of this specific solution, which is discussed [here](https://mail.mozilla.org/pipermail/sync-dev/2016-September/001457.html), but the "http[s]://" prefix mentioned in there didn't work. the domain name itself without prefix, however, did.
