### ISSUE TITLE
tests in test/local/lib/senders are not being run

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1727]
https://github.com/mozilla/fxa-auth-server/tree/master/test/local/lib/senders

The default `npm test` resolves to `mocha test/local/* test/remote/*`.

But that globbing does not include `test/local/lib/*`, ya?

The tests in there do appear to pass, but 
1. put a `throw` in a test in e.g., test/local/lib/pool.js 
2. run `./node_modules/.bin/mocha test/local/*  test/remote/*` => tests pass
3. run `./node_modules/.bin/mocha test/local/* test/local/lib/* test/remote/*` => tests fail

(I was looking at this because there's a bug with how config is loaded now that auth-mailer is part of auth-server, and test/local/lib/email.js should fail, but doesn't. But I'll wait on getting the mocha run fixed before getting back to that).

**Comment by philbooth** [comment]
😱 Good catch. This is my fault, sorry. Fixing now.

**Comment by philbooth** [comment]
> ...there's a bug with how config is loaded now that auth-mailer is part of auth-server...

@jrgm, I'm responsible for a lot of the monkeying-around that happened here and may be able to help fix it. To summarise the intent behind the changes:

* `config` and `mailer/config` were kept separate (for now) because they use different property names for the same settings.

* To allow separate configs to be used, there are two entry-point modules for the old mailer source, `lib/senders/legacy_index` and `lib/senders/index`.

  * `lib/senders/legacy_index` and the rest of the mailer source expect config in the old `mailer/config` format. So anything that requires those directly should get config from `mailer/config`, e.g. `bin/mailer_server.js`.

  * `lib/senders/index` marshalls config property names to the old `mailer/config` format, so that auth server code can continue loading config from the root. So anything that requires `lib/senders` should get config from the root.

* Going forward, the plan was/is to gradually eliminate the dependencies on `mailer/config` and then eliminate `lib/senders/legacy_index`. At this point we can get rid of `mailer/config` entirely.

Does that make sense?

And really sorry, I should have raised all this in a meeting, I now realise. I stupidly assumed I was changing things in a way that meant nothing would break. Does the above help explain whatever bug it is you're seeing?
