### ISSUE TITLE
flaky test remote sms (mocked nexmo) POST /sms success

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1842]
```
  763 passing (3m)
  1 failing

  1) remote sms (mocked nexmo) POST /sms success:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

```

**Comment by vladikoff** [comment]
Example: https://circleci.com/gh/mozilla/fxa-auth-server/462

**Comment by philbooth** [comment]
I've been eyeballing the code to try and figure this one out but don't see much at the moment.

One thing I'm wondering, is it possible that the config gets messed up somehow so it tries to call the real nexmo rather than our mock implementation?

https://github.com/mozilla/fxa-auth-server/blob/25906317ec38394f0a2188c03acf3b6c15d955d9/lib/senders/sms.js#L17

**Comment by philbooth** [comment]
Is it flaky? Or is it permafail? I'm 3 for 3 on my current branch, digging into it again now.

**Comment by philbooth** [comment]
I've been playing around a bit, adding logging to try and see what's going on. If the log output order can be trusted (not sure if there's any buffering of test output), it looks like the call to `Client.create` might be the slow bit for some reason:

```
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․DEBUG: calling Client.create
!DEBUG: calling client.smsSend
DEBUG: sending sms
DEBUG: finished sending sms
․․DEBUG: sending sms
․DEBUG: asserting
DEBUG: done
․․․․

  765 passing (3m)
  1 failing

  1) remote sms (mocked nexmo) POST /sms success:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Obviously that's a deeply unintuitive result because that code is the same as all the other tests, hence my uncertainty about whether it can be trusted.

But fwiw it's repeatable, every time the `!` for the timed-out test shows up before the log message preceding the call to `client.smsSend`.

**Comment by philbooth** [comment]
> But fwiw it's repeatable, every time the `!` for the timed-out test shows up before the log message preceding the call to `client.smsSend`.

Actually, I just saw one where it made it to `client.smsSend` before the test timed out:

```
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․DEBUG: calling Client.create
DEBUG: calling client.smsSend
!DEBUG: asserting
DEBUG: done
․․․․․․․

  765 passing (3m)
  1 failing

  1) remote sms (mocked nexmo) POST /sms success:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by philbooth** [comment]
> ...is it possible that the config gets messed up somehow so it tries to call the real nexmo rather than our mock implementation?

That doesn't appear to be the issue:

```
․DEBUG: smsConfig.useMock true
DEBUG: calling Client.create
DEBUG: calling client.smsSend
!․․DEBUG: asserting
DEBUG: done
```

**Comment by vbudhram** [comment]
> Is it flaky? Or is it permafail? I'm 3 for 3 on my current branch, digging into it again now.

FWIW, seen this a lot today, at least 5 for 6. Can not seem to replicate it locally though.
