### ISSUE TITLE
Allow metrics to link flows either side of the SMS message for connect another device

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1945]
Measuring phase 2 of connect another device was tricky because we had no way to link the flow that signed up for an account with the flow that connected a second device. The best we could do was join on `uid` and impose a time limit, which left us unable to properly diagnose the infamous dip of May 24th.

One way we could fix this for phase 3 (HACK MODE: ON) would be to store the originating flow id in the `signinCodes` table. Later, when we consume the signinCode, the auth server could emit some kind of `flow.continued.from` event and, for that event only, overload one of the other event properties so that the two flows can be linked together in redshift.

There is one other column in the `flow_events` schema that, like `flow_id`, is defined as `VARCHAR(64)`: `uid`. Would it be completely hackish and abhorrent to overload `uid` on this one event only, so that we could link two flows together without needing to change the metrics pipeline or the import scripts or the existing dumped CSVs?

If `uid` is considered too ugly, perhaps it would be semantically more agreeable to overload `entrypoint` instead? That would necessitate tweaking the redshift schema to make it `VARCHAR(64)`, but would have the benefit of perhaps not seeming quite as odd to anyone looking at the code or the metrics in the future.

Or maybe the whole approach is too sinful and we should do something else? I'm fine with that.

/cc @shane-tomlinson

**Comment by rfk** [comment]
> store the originating flow id in the signinCodes table.

I like this part; we could also consider memcache is we didn't want to do a db schema change, but either way 👍 

> Would it be completely hackish and abhorrent to overload uid on this one event only,
> so that we could link two flows together

I dunno, this seems like a recipe for confusion.  IIRC the `uid` is a property of the flow as a whole, not a specific event, so would this prevent us from associating the *actual* uid with that flow when it completes?

> perhaps it would be semantically more agreeable to overload entrypoint instead?

This seems nicer to me, perhaps we could even make it "continue:<flow_id>" or similar so that it's easy to match on with a `LIKE 'continue:%"'.

> without needing to change the metrics pipeline or the import scripts or the existing dumped CSVs?

I'm sad that we have to hack around our tools here :-(

@philbooth IIRC you previously tried to manage schema changes in the import scripts right, e.g. by using a different set of fields depending on what day was being imported?  Was this basically just a maintenance nightmare in practice?

**Comment by philbooth** [comment]
> ...would this prevent us from associating the *actual* uid with that flow when it completes?

It wouldn't but don't worry, even as I thought/typed that suggestion, I was disgusted with myself for thinking it.

> ...perhaps we could even make it "continue:<flow_id>" or similar so that it's easy to match on with a `LIKE 'continue:%"'.

Good point. Actually, this makes me realise we could also just stick it in the event name itself, like we do for loads of other variables that don't have first-class properties on the event object. View name, experiment name etc. Then the schema remains unchanged. Why didn't that occur to me yesterday?

> IIRC you previously tried to manage schema changes in the import scripts right, e.g. by using a different set of fields depending on what day was being imported? Was this basically just a maintenance nightmare in practice?

Yeah, I don't remember exactly what the problem was now but I know I struggled to get `COPY` working conditionally in the SQL for some reason. It's possible I didn't try hard enough but I ended up running a script to pad all the old CSVs with an extra comma instead.

Maybe it was specifically in the case where we have to go back and re-import older data to the newer schema or something?

**Comment by philbooth** [comment]
> Actually, this makes me realise we could also just stick it in the event name itself... Then the schema remains unchanged.

Erk, no it doesn't. `type` is only `VARCHAR(64)` itself. I'll stick with `entrypoint`.

**Comment by rfk** [comment]
> type is only VARCHAR(64) itself.

Could we increase this just by changing the db schema, rather than having to adjust all the existing CSV files.  Perhaps we could do something like:

* Increase size of `type` column so we can fit in a "continue:flow_id" event
* Add a "continued from" column of some type to flow_metadata table
* Add an extra step to the post-processing of imported flow data, that looks for the "continue:flow_id" event, and fills in the corresponding column in the flow_metadata table

It seems like this could avoid the main pain-point of adjusting the format of the CSVs.

**Comment by philbooth** [comment]
> Could we increase this just by changing the db schema, rather than having to adjust all the existing CSV files.

Yep, that was what I was already planning to do with `entrypoint`. Happy to do it with `type` instead. Changing a column definition is not difficult at all, it was adding new columns that I've had trouble with.
