### ISSUE TITLE
Email: Use deeplinks in email confimation when triggered from mobile to send users back into Firefox

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1969]

**Comment by shane-tomlinson** [comment]
@seanmonstar - is this for the marketing buttons?

**Comment by seanmonstar** [comment]
I admit I don't fully know the details, I was just creating the issue by going through the backlog spreadsheet. It's possible this is a duplicate of an issue that had a different name.

**Comment by rfk** [comment]
I'm not sure about this one to be honest - IIUC it's asking us to make the "confirm sign-in" link into an adjust deeplink, and I see two potential problems with this:

* It passes account verification codes to Adjust, so we'd have to consider security and PII implications
* If they happen to be signing in on a mobile device but check their email on a desktop device, then the deeplink will not do the right thing

What *might* be an interesting idea here is, when the user has firefox installed on their mobile device, do set up config to cause "accounts.firefox.com" to always open in Firefox rather than in the default system browser.  But I can easily imagine this having unforseen consequences.

**Comment by vladikoff** [comment]
Let's revisit this if still needed.
