### ISSUE TITLE
Newly created accounts can add emails on any browser

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2181]
Not sure if this is an issue but wanted to document it since I ran into it while working on https://github.com/mozilla/fxa-content-server/issues/5592. Currently, newly created accounts will always create verified sessions for the first X hrs. This was added so that users could login without having to do sign-in confirmation on new devices.

A side effect is that users can also add secondary emails during this time since that feature requires verified sessions. This could explain why Datadog showed views of the emails panel in non-Firefox browsers.

I think the current functionality is good and we shouldn't have any additional restrictions for new accounts. I would want them to add as many things as possible during this timeframe.

Is there any reason to restrict creating verified sessions for new accounts to only Firefox? 

cc @davismtl

**Comment by davismtl** [comment]
I don't see any problem with this but I'll kick it to @rfk who often has good insights on this stuff.

**Comment by rfk** [comment]
Nice catch.  But please file questions about potential security issues somewhere non-public, such as a security-sensitive bugzilla issue or a post to fxa-staff 😅 

I think we're OK here though.  During this window, it's already possible for an attacker who knows the user's login credentials to sign in to sync without an email verification loop.  Allowing them to also add/change emails on the account does open up some new possibilities.  They could:

* Change the password and primary email, and lock you out of the account.
* Change where emails are delivered so that you don't get the "new signin to firefox" warning email when they try to access your sync data.

What emails will the legitimate owner of the account see, if an attacker tries to use this capability to take over the account?  As long as these emails will trigger an appropriate "oh crap someone else is accessing my account" response in the account owner, this seems OK to me.  I think it's hard to argue that "adding  a new email" should be special-cased into a higher security level than "accessing your sync data".

**Comment by vbudhram** [comment]
> What emails will the legitimate owner of the account see, if an attacker tries to use this capability to take over the account?

They would get notifications that an email was added or removed from account. Once https://github.com/mozilla/fxa-auth-server/issues/2153, lands they will also get notifications that primary email has changed. Each one of those emails does tell the user that "oh crap someone else is accessing my account", so we are good on the front.

Those things considered, I am marking this closed and not changing current functionality. Not sure why the security nature of this skipped my mind but glad nothing is changing 😅.
