### ISSUE TITLE
devices.marshallLocation.error: Cannot read property 'city' of undefined

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2199]
Happened to notice there are quite a few of these errors in the logs in stage. The error is handled, but maybe not the optimal diagnosis. Or perhaps there's a real bug here, and location should never be undefined in marshallLocation.

`
{"Timestamp":1509564625194000000,"Logger":"fxa-auth-server","Type":"devices.marshallLocation.error","Severity":2,"Pid":1,"EnvVersion":"2.0"\
,"Fields":{"op":"devices.marshallLocation.error","err":"Cannot read property 'city' of undefined","languages":"en-US,en;q=0.5","language":"\
en"}}
`

**Comment by philbooth** [comment]
Well spotted, thanks.

It's failing because the parsed language has extra (escaped?) whitesace at the start, so the test for English fails and then the attempt to dereference `territories` in `cldr` fails too. I could add a `trim` but also I wonder if I'm using `i18n-abide` wrong for it to return that to me? I see that there's a `normalizeLanguage` method that I'm not using, but it doesn't appear to strip whitespace.

Anyway, digging in now...

**Comment by philbooth** [comment]
> it's failing because the parsed language has extra (escaped?) whitesace at the start

Wait, that's not right because it's dereferencing `city` which happens inside the English condition. But that language property in the error message does look wrong, I'm surprised it passed:

```
"language":"\ en"
```
