### ISSUE TITLE
Enable USE_REDIS=true in CI tests?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2280]
We currently specify `USE_REDIS=false` in the environment for `npm run test-ci`.  Should we aim to switch it to `USE_REDIS=true` to ensure we're getting proper coverage the redis codepaths, or perhaps even running variants with both `false` and `true`?

I tried just switching it to `true` over in #2279, but it caused some test failures, so I figured I'd spin it out into a separate issue for digging into later.

**Comment by philbooth** [comment]
I think the test failures you were getting might have been caused by something else because the tests that need redis enabled enable it internally and the ones that need it disabled it do that internally:

```
$ git grep config.redis -- test/
test/remote/account_locale_tests.js:config.redis.enabled = false
test/remote/account_signin_verification_tests.js:config.redis.enabled = false
test/remote/certificate_sign_tests.js:config.redis.enabled = false
test/remote/db_tests.js:  redis: Object.assign({}, config.redis, { enabled: true }),
test/remote/db_tests.js:  host: config.redis.host,
test/remote/db_tests.js:  port: config.redis.port,
test/remote/db_tests.js:  prefix: config.redis.sessionsKeyPrefix,
test/remote/redis_tests.js:const redis = require(`${ROOT_DIR}/lib/redis`)(Object.assign({}, config.redis, { enabled: true }), log)
test/remote/redis_tests.js:    const redisPool = require(`${ROOT_DIR}/lib/redis/pool`)(config.redis, log)
```

I don't think setting the var was having any effect. It was probably added out of caution when we were first depending on Redis and not everywhere had been updated to run it.

Anyway, PR opened at #2281.
