### ISSUE TITLE
TOTP Management APIs

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2293]
#### POST /totp/create

:lock: HAWK-authenticated with session token

Create a new TOTP token for user.

##### Request body

* {}

##### Response body

* `qrCodeUrl`
  * The encoded shared secret for the TOTP token

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: 105`: Unverified Account
* `code: 400, errno: XXX`: Duplicate token

#### POST /totp/destroy

:lock: HAWK-authenticated with session token

Delete TOTP token for user.

##### Request body

* {}

##### Response body

* {}

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: 105`: Unverified Account
* `code: 400, errno: XXX`: Unknown token
  
#### POST /session/verify/topt

:lock: HAWK-authenticated with session token

Check to see if a TOTP code is valid and then verify corresponding session.

##### Request body

* `uid`: *string, max(32), regex(HEX_STRING), required*
  * The uid associated with the token code
* `code`: *string, min(6), max(6), required*
  * The 6 digit TOTP code
* `recoveryCode`: *string
  * Recovery code to verify this session

##### Response body

* {}

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: XXX`:
  Invalid authentication token

**Comment by rfk** [comment]
@vbudhram I had a question that come out of your awesome demo earlier today - can a user safely bail out of the TOTP setup process once it has begun?  Here's a scenario:

* I go to `/settings` and click to enable TOTP
* The page calls `/totp/create` to add the TOTP token and obtain the QR code to display
* I'm weirded out by the QR code, start reading the linked help page on TOTP, realize I need an app on my phone, and decide it's all too hard
* I close the browser tab and go back to whatever I was doing

Have I just unwittingly bricked my account?

IIUC from the flow here, the TOTP token was already added to my account at the point where I saw the QR code, because it's generated by the `/totp/create` method.  So if I abandon the flow at that point, then my next login attempt will see that there's a TOTP token on my account and will insist that I use 2FA [1].  But I can't, because I never finished setting it up.

I'm wondering if there needs to be some sort of `POST /totp/confirm` API that confirms you were able to generate a proper TOTP verification code, and only activates TOTP on your account once you've done so.


[1] https://github.com/mozilla/fxa-auth-server/pull/2300/files#diff-ab87c506e682e952973178a41792df12R438

**Comment by vbudhram** [comment]
> can a user safely bail out of the TOTP setup process once it has begun?

This is definitely a requirement that I was hoping to add as part of https://github.com/mozilla/fxa-auth-db-mysql/issues/301. I was thinking of adding a `verified` and `enabled` column to help ensure that the user doesn't get into any strange intermediate states with TOTP tokens.

As you stated, there is a chance that a user could brick their account as the code currently is. However, as long as they are in a verified sync session, they can delete the token.

> I'm wondering if there needs to be some sort of POST /totp/confirm

That sounds reasonable to me. My plan was to use the `/session/verify/totp` endpoint to verify and confirm the token, but I don't see any harm in having an explicit one.

**Comment by rfk** [comment]
> I was thinking of adding a verified and enabled column to help ensure that the user doesn't
> get into any strange intermediate states with TOTP tokens.

Cool, sounds 👍 to me :-)
