### ISSUE TITLE
Add API support for recovery key

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2421]
#### POST /recovery_key

:lock: HAWK-authenticated with session token

Creates a new recovery key for the user.

##### Request body

* `recoveryData`: *string, regex(HEX_STRING), required*
* `recoverykId` : *string, max(32), required*

##### Response body

* `{}`

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: 105`: Unverified Account
* `code: 400, errno: XXX`: Key already exists

#### GET /recovery_key

:lock: HAWK-authenticated with session token

Get a user's recovery key

##### Response body

* `recoveryData`: *string, regex(HEX_STRING), required*
* `recoverykId` : *string, max(32), required*

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: 105`: Unverified Account
* `code: 400, errno: XXX`: Unknown key
  
#### POST /recovery_key/destroy

:lock: HAWK-authenticated with session token

Removes an recovery key

##### Request body

* `uid`: *string, max(32), regex(HEX_STRING), required*
* `recoverykId`: *string, max(32), regex(HEX_STRING), required*

##### Response body

* {}

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: XXX`: Invalid authentication token

child of mozilla/fxa#297

**Comment by rfk** [comment]
> GET /recovery_key
> 🔒 HAWK-authenticated with session token

Part of the idea of the "recovery key id" is that the caller must provide the id in order to obtain the recovery data, as a kind of "proof of possession" of the underlying secret.  So I think this will need to be `GET /recovery_key/<kid>` or equivalent.

I don't think it can be authenticated with a sessionToken; the user calling this has forgotten their password and hence may not be able to obtain a sessionToken.  Perhaps we can authenticate it with a passwordResetToken or accountResetToken, although we'll have to be careful because those are supposed to be single-use.

This endpoint also needs to be rate-limited, to help prevent brute-force guessing of recovery keys.
