### ISSUE TITLE
Emit account recovery key metrics

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-auth-server#2538]
cc @vbudhram 

With https://github.com/mozilla/fxa/issues/297 well into development its important that we make sure we implement all the metrics we need to know in order to gauge its success.

~~Right now, I've seen the following auth server events emitted (see [this chart](https://sql.telemetry.mozilla.org/queries/57458/source#149799)):~~

~~* `recoveryCode.replaced` fired when a new code is generated?~~
~~* `recoveryCode.verified` fired when a code is used?~~
~~* `flow.signin-recovery-code.view` view of prompt to signin to generate code?~~
~~* `flow.signin.signin-recovery-code.view` view of prompt to enter code during signin?~~

~~Two things:~~

~~1. Can someone verify that my description of the existing events are more-or-less correct?~~

(events above were related to 2fa recovery codes, we should be sure to name the new events below to be distinct from those)

2. Based on conversation with @medinacana and @davismtl I think, at a minimum, we'll need to make sure that the following flow events are recorded:

(note that the names here are just examples, if they need to be something else due to technical reasons that's fine)
**Code Creation/Management Flow Events**
- [ ] `flow.account-recovery.view` user views the screen containing the "generate" button (thru settings)
- [ ] `flow.account-recovery.signin.view` user views the screen requiring them to enter a password before receiving a code
- [ ] `flow.account-recovery.signin.submit` user submits their password on view above
- [ ] `flow.account-recovery.code.view` user views the screen containing the recovery code

**Code Use During Signin Flow Events**
- [ ] `flow.signin.recovery-code.view` user views the form to enter a recovery key after requesting a password reset
- [ ] `flow.signin.recovery-code.reset-password.view` user views the form to reset their password after having entered their recovery key
- [ ] `flow.signin.recovery-code.reset-password.submit` user submits the form to reset their password after having entered their recovery key

**Events Regarding Code Use**
- [ ] `recoveryCode.created` a recovery code is created
- [ ] `recoveryCode.consumed` a recovery code is used (only needed if not covered by `recoveryCode.verified`) also means a password was successfully reset. 
- [ ] `recoveryCode.revoked` a recovery code is revoked
- [ ] `recoveryCode.download` user downloads a recovery code
- [ ] `recoveryCode.copy` user copies a recovery code
- [ ] `recoveryCode.print` user prints a recovery code

Also, can we verify that we will get `route./recoveryCodes.XXX` type events on errors related to invalid codes?

Additional events that may be nice to have include those associated with code generation/consumption/revocation emails. 

We also need to make sure versions of these make it into amplitude as well. once we know that some version of these events can be measured, I'll update the amplitude taxonomy with the correct parameters.

@medinacana can you verify that the list of above events are sufficient to track the success metrics we care about and align with our plans for the UX?

**Comment by philbooth** [comment]
> - [ ] `flow.signin.recovery-code.view` user views the form to enter a recovery key after requesting a password reset
> - [ ] `flow.signin.recovery-code.reset-password.view` user views the form to reset their password after having entered their recovery key
> - [ ] `flow.signin.recovery-code.reset-password.submit` user submits the form to reset their password after having entered their recovery key

Quick drive-by on the apparent naming convention used here, is it important we use these particular event names?

I ask because the logic for emitting view/submit/engage events has been quite heavily generalised at this point to reduce repetition in the content server codebase. So the code for emitting the event names you have above will be messier than a plain `flow.${view-name}.view` or whatever.

I get that you want to distinguish between the same view name at different points in the flow, but can that be inferred a different way? (e.g. by setting other properties in `flow_metadata` or by joining against earlier events from the flow)

(it's not the end of the world if you can't, just wanted to ask the question)

**Comment by irrationalagent** [comment]
The particular names aren't important (maybe as long as they are somewhat interpretable). Is the issue the signin.XX.YY.view format? From the UX it appeared that the `reset-password` view here is distinct from the typical reset password form, so I was assuming that it would at least get a distinct name. If it doesn't that's ok, as you said we can manage it on the analysis end.

**Comment by medinacana** [comment]
I think you covered the majority of what we spoke about. 
I just wanted to clarify that

**Comment by philbooth** [comment]
> Is the issue the signin.XX.YY.view format?

Yeah, essentially the middle chunk of those events has to be the literal view name as it is in the content server code right now. I don't know enough about this flow to know what those view names are at this point, so maybe I'm raising a non-issue, but just wanted to flag it as I read your comment. When @vbudhram is back he might have more to say on it.

**Comment by medinacana** [comment]
@irrationalagent I think you've covered the majority of the metrics we spoke about yesterday. 

I just wanted to clarify if any of the above events would track:
- When people click **Learn More** on the generate recovery key screen. We added this copy in the new UX, so I wanted to track if people click it, and if we should keep it there. The initial design doesn't include it, so it may be good to measure for the experiment. 
- When people click **Lost recovery key?**. We might want to track this so we can track if people are losing the recovery key they are generating. 

Also, are we tracking how many people want to create a new recovery key after consuming their recovery key? They will be prompted to create a new recovery key once they reset their password and via email, I wonder if we should measure if people click either one of those prompts. 
Otherwise, we can always look at `recoveryCode.consumed` and then `recoveryCode.created`, right? Or is sequence of events measured with `recoveryCode.replaced`?

**Comment by irrationalagent** [comment]
@medinacana do both the learn more and lost recovery key buttons link to a url/webpage? or do they lead to another view in the flow?

as for generating a new recovery code, yes we can simply create a funnel where `recoveryCode.created` follows `recoveryCode.consumed` so I don't think we need to add another event. when Vijay get's back we'll find out what `recoveryCode.replaced` means.

**Comment by medinacana** [comment]
@irrationalagent The learn more would be a pop up page with more information about the feature. 
Lost Recovery key would lead you to another screen in the flow, where the user would have to reset their password without the recovery key.

Ok, awesome, thanks!
