### ISSUE TITLE
fix Mailer.prototype.selectEmailServices to respect injected mock sender

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2662]
re: https://github.com/mozilla/fxa-auth-server/pull/2661#issuecomment-429442936

Running ./scripts/bulk-mailer.js without the `--send` parameter set was supposed to mean that a mock sender would be used and no actual emails sent. But, in stage, redis had an `email:config` key set, and that resulted in a real live-email sender being used (but only with my test email addresses so no test spam was sent out that mattered).

The Mailer.prototype.selectEmailServices is here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/email.js#L427 and you can see that if `liveConfig` is found, `this.mailer` is ignored.

**Comment by philbooth** [comment]
I haven't looked at @shane-tomlinson's script yet but I suspect it will be easier to patch that to set `this.emailService` at the same time as it sets `this.mailer`, than to give `selectEmailServices` a way to detect that `this.mailer` is a special mocked case. It may also be the more durable long-term change too, since we'll be removing `selectEmailServices` soon (probably Q1) and giving `this.emailService` carte blanche for handling all email traffic.

**Comment by philbooth** [comment]
This got fixed in #2470.
