### ISSUE TITLE
Merge auth-server and oauth-server 🛠

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2668]
It was a long time proposal from @rfk to uplift the oauth-server into this repo. With the recent exploration into improving devices API I think we finally got to the point where it is worth doing this to make it easier to develop new OAuth features. Let me know if you are against this idea in the comments below. Otherwise Like and Subscribe.

I began work on syncing up dependencies in:

https://github.com/mozilla/fxa-oauth-server/pull/615
https://github.com/mozilla/fxa-oauth-server/pull/616

**Comment by philbooth** [comment]
Woop! Can we merge fxa-auth-db-mysql in too?!

**Comment by rfk** [comment]
@rfk to merge with other bug about this

**Comment by rfk** [comment]
I accidentally created a dupe of this over in https://github.com/mozilla/fxa-auth-server/issues/2679, but this one has emoji so I'm going to close out https://github.com/mozilla/fxa-auth-server/issues/2679 and migrate its checklist over to here.

**Comment by rfk** [comment]
Actually no, this issue is different and broader than https://github.com/mozilla/fxa-auth-server/issues/2679; this issue is talking about actually merging the two servers together, while https://github.com/mozilla/fxa-auth-server/issues/2679 is a pre-req about making them a monorepo.  Let's push forward on the work in https://github.com/mozilla/fxa-auth-server/issues/2679 first and we can pick up this one again when @vladikoff returns.

**Comment by vladikoff** [comment]
Remaining work is in https://github.com/mozilla/fxa-auth-server/issues/2748
