### ISSUE TITLE
Update verification email for non-Sync FxA reliers

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#2859]
Current:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/68213/51000132-22d0ce80-14fa-11e9-8300-9dd7f7d29bbf.png">

Proposed:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/68213/51000154-33814480-14fa-11e9-86da-983f176f2d46.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson This is a lockbox team request.

**Comment by vladikoff** [comment]
thought we had this, need to debug...

**Comment by shane-tomlinson** [comment]
@ryanfeeley - The sync banner should only be displayed if `?service=sync` is specified as a query parameter on signup. If they aren't specifying `service=sync`, they won't get it.

We do not yet have the "Welcome to %(serviceName)s", what's the chance that would cause confusion? "Welcome to Lockbox! Confirm your Firefox Account..."

**Comment by ryanfeeley** [comment]
@shane-tomlinson  I don't think it's be confusing.

I just created a Firefox Account for screenshots and got this…

<img width="650" alt="image" src="https://user-images.githubusercontent.com/68213/51275534-3e2b5600-19a0-11e9-95fe-161309ca7b02.png">

**Comment by shane-tomlinson** [comment]
The email as is is obviously confusing, there are a couple of issues at play. 

First, I'm really confused why that Sync photo is being displayed. It should only be displayed for [Sync signup](https://github.com/mozilla/fxa-auth-server/blob/1356749ad007788d50748580115aa833755b6fa7/lib/senders/templates/verify.html#L18). Users of other services should see the [Firefox logo](https://github.com/mozilla/fxa-auth-server/blob/1356749ad007788d50748580115aa833755b6fa7/lib/senders/templates/verify.html#L14).

<img width="150" src="https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/firefox57-logo.png">

Second, the service name does have a place in the email since it ties FxA and the service together, I'm just not convinced the suggestion is right, the two services aren't linked through language, only proximity. I'm thinking back to the Persona experiment where users were confused seeing the service name/logo within the Persona UI, there was a similar problem there. The user is obviously trying to get back to the service, and landing on an FxA only screen is confusing.

I'm not a text wizard, I wonder if something like this could work:

"Welcome to %(serviceName)s! <br/> Confirm this email address to activate your Firefox Account and continue to %(serviceName)s."

**Comment by vladikoff** [comment]
this email bug might be due https://github.com/mozilla/fxa-auth-server/pull/2868#event-2079278570 

this is because we fallback to sync if something goes wrong fetching the service name

**Comment by ryanfeeley** [comment]
> "Welcome to %(serviceName)!
> Confirm this email address to activate your Firefox Account and continue to %(serviceName)s."

This is better. I like that we continue to use continue to language.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Updated
<img width="728" alt="image" src="https://user-images.githubusercontent.com/68213/51400296-0ba36980-1b16-11e9-9c32-79efa4fbe53b.png">

**Comment by shane-tomlinson** [comment]
This is going to be slightly more challenging than I thought. On the auth-server's mailer code we have the client ID, not the service name.  We'll need to be able to translate from client ID to service name, which if we don't have the info already, we could do by calling the `GET /client/<clientID>` endpoint on the OAuth server.

**Comment by philbooth** [comment]
Might be easier to read it from config instead?

https://github.com/mozilla/fxa-auth-server/blob/19593176575d964d0c47282498bbe55808426ee5/config/index.js#L585-L590

**Comment by philbooth** [comment]
(although the mappings in config aren't canonical/authoritative so it's a lot more error-prone than hitting the OAuth server)

**Comment by shane-tomlinson** [comment]
> Might be easier to read it from config instead?

Luckily, someone [has already done the hard work](https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/email.js#L645) and I can just re-use that!
