### ISSUE TITLE
Auth Server Remote tests are slow 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2960]
Auth Server Remote tests take a while on my machine, not sure how bad on the CI, but might be something to bring to attention

**Comment by philbooth** [comment]
Fwiw I tend to see this as a feature. The remote tests are supposed to be slow because they're essentially integration tests, there to test the correctness of the system. It's the local/unit tests that need to be fast because their job isn't to prove correctness as much as it is to aid rapid development/refactoring.

But I realise my opinions are not always shared when it comes to the tests in FxA, so feel free to disregard!
