### ISSUE TITLE
Tagging "flows"

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#303]
We'd like to distinguish a create flow from a login flow and try to detect whether users complete the create flow or how far they get. Normally the create flow isn't distinguishable from login. The create account event is a single call followed by a normal login flow.

One idea is to tag the account as new so we can track when each endpoint is first hit and mark those as part of the create flow.

Other timer based tagging may also be useful. For instance tag all endpoints for an account starting with a `/auth/start` for X minutes as a single "flow"

**Comment by rfk** [comment]
@kparlante does this bug still reflect your current needs?  Let's either start pushing it forward or close it out.

**Comment by kparlante** [comment]
Here's the motivator: it would be good if we could look at kibana auth log data to answer the question: how many people signed in? Via what service? On what platform? In what language?

We can't really tell because /account/login gets called on both "create/sign up" and "sign in" flows.

We have some visibility from client metrics, but that only covers desktop/browser scenarios, we won't see mobile devices.

The proposal in this bug was for the server to detect the scenario; an alternative would be to ask the client to pass that in directly. It would be helpful to ask for "service" to be passed in as well.

@rfk we could close this bug out and log new bugs once we've agreed upon the strategy, or just work within this bug.

**Comment by rfk** [comment]
Let's figure out what needs to happen in this bug, file more concrete issues for the work, then close out this ancient metabug.  Assigning to me to drive the process.

**Comment by shane-tomlinson** [comment]
@kparlante, @rfk - oh, this is awesome. I was thinking of this *exact* idea because of #876. Right now, login notifications are only supposed to be sent if the user is signing in a new device for Sync. I have to take care of this in client code on the content server (See https://github.com/mozilla/fxa-content-server/pull/2129 and in particular the comment at https://github.com/mozilla/fxa-content-server/pull/2129/files#r25786669). This logic seems like a natural fit for the auth server. Deciding which users see notification messages should be the responsibility of the auth server, not the content server. 

My initial idea was the same as @kparlante and @dannycoates outline - send a "flow" or a "reason" along with the login. The auth server can then decide whether to send a notification email. The new field  can be logged, and finer grained queries can be produced.

**Comment by rfk** [comment]
I would be happy to see the client explicitly pass in more details here.  For a variety of reasons it would be nice to know who, what, and why for each sessionToken we create:

* Who?  Was this a desktop client, your phone, or some random oauth login?  One day we'll probably want to display this information in a "these things are connected to your account" kind of way.  Having the client submit a description of itself doesn't seem crazy to me.
* What?  This is basically what we're trying to work out via the `service` parameter.  It's good for metrics and its good for sending activity emails.
* Why?  Was this done as part of an account create, a normal login, a password reset...?  I guess we're only interested in this for metrics purposes, but it's important.

ISTM the most direct way to track these is for the client to include `device`, `service` and `reason` parameters in the request.  Ugly, but practical.  @shane-tomlinson would this clear up some of your concerns around code factoring in https://github.com/mozilla/fxa-content-server/pull/2129?

(We could also bikeshed about whether these things should live in the query string, request body, or whatever else...but let's not dive into that level of detail just yet.)

**Comment by shane-tomlinson** [comment]
>  @shane-tomlinson would this clear up some of your concerns around code factoring in mozilla/fxa-content-server#2129?

It sure would.

> Having the client submit a description of itself doesn't seem crazy to me.

@ryanfeeley asked that we send a device name whenever we send out the "additional Sync device" emails, a device name would make this possible. Keeping track of this info would also make a "device dashboard" possible - we could add functionality like "Device stolen? Disconnect it."

> Why? Was this done as part of an account create, a normal login, a password reset...? I guess we're only interested in this for metrics purposes, but it's important.

We are interested in the why for both metrics, and for notification emails. For example, signin is called to 1) sign a user in, 2) after a password reset, and 3) after a pasword change. We only want to send "additional sync device" emails for 1.

I could see this work broke into two parts, first to add the "why" because its need is more immediate, then to add the "who".

Going to ponder a more concrete proposal.

**Comment by rfk** [comment]
> I could see this work broke into two parts, first to add the "why" because its need
> is more immediate, then to add the "who".

On the backend side, it probably makes more sense for us to add them all at once, for example so it can be done in a single DB migration.  But we'd have to provide sensible defaults for any info not provided, so support in various clients could follow piecemeal.

**Comment by shane-tomlinson** [comment]
@rfk - a concrete proposal:

1. We can use "why" information for more than just tagging flows. Let's make the why explicit, and pass a new field, `reason` when calling `/account/login`.
  1. `reason` can be one of: `login`, `change_password`, or `reset_password`. If no `reason` is specified, assume `login`, or try to use some timing based heuristic to see if a change password or password reset verification was the last action taken by the user.
1. "who" can also be used for more than metrics, e.g., in an account dashboard that shows a list of logins and connected devices. This information can initially be determined from the UA string of the request. At some future point we may want to surface UI asking the user to name their device. If a UA string is not sent, default to `unknown device`.

How the information is stored is beyond the scope of this straw-man proposal and can be spec'ed once the information needed is agreed upon.

**Comment by rfk** [comment]
Just to sanity-check an assumption here - is it true that the sign-up flow calls `/account/login`?  The `/account/create` endpoint returns a `sessionToken` directly so there's really no reason why it should have to.

**Comment by rfk** [comment]
For `reason` we may also be able to identify "re-establishing a session due to password change on another device" as a separate category that should not send a notification email.

**Comment by rfk** [comment]
Alternately, is what we're getting at with `reason` just "this is a fresh session" versus "re-establishing an existing session"?  Do we need to distinguish nuanced sub-cases of re-establishment here?

**Comment by ckarlof** [comment]
> Just to sanity-check an assumption here - is it true that the sign-up flow calls /account/login? The /account/create endpoint returns a sessionToken directly so there's really no reason why it should have to.

[It used to](https://github.com/mozilla/fxa-content-server/pull/1963).

**Comment by rfk** [comment]
Right, and I guess this is what #736 is refering to when it says "optimize this ... like we did for `account/create`."

**Comment by shane-tomlinson** [comment]
> Right, and I guess this is what #736 is refering to when it says "optimize this ... like we did for account/create."

If #736 is implemented, and we do the same for `change_password`, then `reason` might not make much sense. We could say whether it's a fresh session or re-establishing a session, and only send Sync Sign-In notifications on fresh sessions, but we do not give Sync users the option to sign out.

**Comment by rfk** [comment]
The trouble with doing #736 in conjunction with the other changes here, is that we'd have to send additional session metadata on those requests as well.  It might make for an overall messier API.

**Comment by rfk** [comment]
We now have 'service' and 'reason' parameters passed to the login endpoint, I don't think there's more for us to do here.
