### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#750]
Tracking issue. One thought it is that if user has 2FA enabled, then we we may not require it for *all* services/actions.

**Comment by shane-tomlinson** [comment]
Closing, this is now tracked in Aha.io.

**Comment by mlissner** [comment]
Is there a way to follow the progress of 2FA for Firefox Sync? Aha.io doesn't look friendly to outsiders (surprising considering FF's general ethos).

**Comment by rfk** [comment]
> Aha.io doesn't look friendly to outsiders

Indeed it's not, but I'm hoping we'll find a way to reflect most of the interesting stuff from it in a more public place.

Concretely, this 2FA work is not currently scheduled for implementation, and we likely won't revisit it until sometime next year (unless one of our reliers shows up with a pressing need for it)

**Comment by mlissner** [comment]
Firefox Sync has the capability to sync passwords. Not even getting into the amount of private data it has (bookmarks, etc), syncing passwords means that it's the linchpin of the security system. I use 2FA in about 20 different sites now because of the added security it provides, but I was pretty shocked to realize today that there was no way to set up 2FA for Firefox. I really hope this can be prioritized.

(Sorry for commenting on a closed issue like this, but I have no idea how else to make a comment on this feature.)

**Comment by rfk** [comment]
Thanks @mlissner - prioritization is always a challenge, but feedback like this is very useful for us to get a sense of how impactful a feature will be.  Something like 2FA is particularly tricky, because based on experiences we've heard from other services, we would expect less than 10% of users to enable the feature.  But those users that *do* enable it feel really strongly that it provides a lot of value.

> (Sorry for commenting on a closed issue like this, but I have no idea how else to make a comment on this feature.)

No problem, this is probably the best place for it for now (which is in itself a problem)

**Comment by mlissner** [comment]
> we would expect less than 10% of users to enable the feature

10% is actually pretty good! My rule of thumb is to enable 2FA on anything that protects money, email, or passwords.

**Comment by banool** [comment]
In the last two years has there been any plans or progress on implementing 2fa? For Firefox Sync and whatnot it seems like a pretty lacking feature. Personally I would be using Firefox Sync instead of LastPass if 2fa was available.

**Comment by rfk** [comment]
Just this very week during the Mozilla all-hands, we discussed making 2FA a top-level priority for Q1 2018, since this:

> (unless one of our reliers shows up with a pressing need for it)

Seems to finally have come true.

**Comment by banool** [comment]
Awesome, great job to the Mozilla team. Looking forward to it!

**Comment by mlissner** [comment]
In case that "relier's" pressing need goes away, I'd just like to throw it out there that before you were syncing passwords, you should have added support for 2FA. It's baffling that this isn't already built in, given the sensitivity of what you store. I'd expect you'd want to offer it just for your own sanity.
