### ISSUE TITLE
Debug Basket API errors

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#839]
We're getting a fair number of Basket API errors: https://bugzilla.mozilla.org/show_bug.cgi?id=1102652#c2

* The most frequent is "invalid language". @dannycoates, can you work with @pmclanahan to figure out what locale strings we're sending that are causing these errors? Currently, we have insufficient logging on the auth server side to reliably see the input causing the error (https://github.com/mozilla/fxa-auth-server/blob/master/bin/basket.js#L39). 

* We're also seeing a number of connection errors (5xx, timeouts, resets). Should we have a retry strategy around these? @pmclanahan, what sort of information do you have on your side about the 5xx errors?

* @dannycoates, do we have any monitoring on the Basket errors?

**Comment by rfk** [comment]
AFAICT from the code, if the request to the basket API fails then it stays in the queue and we'll retry it once SQS magic makes it visible again.  From the SQS config, it looks like we'll be retrying them every 5 minutes for 4 days.

**Comment by rfk** [comment]
Hmm, actually that probably only applies to the connection-level errors, HTTP-level errors will be logged at `INFO` level and the queue item deleted.

**Comment by rfk** [comment]
Some logging for the locale strings has already gone out in a previous train, so if these errors are still happening then we should be able to find them in the app logs.  @jrgm is going to follow up with @ckolos about digging them out of the logs.

**Comment by rfk** [comment]
From taking a look at the basket code and running it on a few examples, the following will trigger the "invalid language" error when passed in the "accept_lang" field:

  * an empty string
  * a valid language code with leading or trailing whitespace, e.g. `" en-US"`
  * a wildcard language code without additional tags, e.g. `"*"` but not `"en-US,*;q=0.1"`

The first could happen since we pass through the `Accept-Language` header unchanged when it's less than 255 chars, so a blank header would show up as an empty string in this API call.

The second could happen if the user submits a long `Accept-Language` header with whitespace in it, like `"en-US , en;q=0.5"` but longer.  In this case our `trimLocale` function could produce a value with trailing whitespace and trigger the error.

The third would be up to basket to decide how to deal with, if we ever actually see that in the wild.

In addition, if we happen to pass a non-string value for `accept_lang` (say `null` or `undefined`) then AFAICT basket will throw an error and most likely give us a 500 response.  I don't think this will happen, but we don't guard against it on either side.

**Comment by rfk** [comment]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1121799#c2 we're seeing instances of:

  * `locale=null`
  * `locale=""`
  * `locale="en_US"`  (which is invalid per RFC 2616; only dashes are allowed in language tags)

All of which will indeed cause errors when submitting to the basket API.

We could do a little more sanity-checking here, but I'm not sure it's worth it given that (a) this is user-provided data, so we can't really help if some of it is invalid, and (b) we plan to iterate on how this data is handed off to basket in Q1.

**Comment by rfk** [comment]
Given #863, https://bugzilla.mozilla.org/show_bug.cgi?id=1102652 and the intention to refactor how these notifications are sent, I don't think there's any more work we can do in this bug.  Closing.
