### ISSUE TITLE
Verification email expired metric is high

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#953]
From metrics meeting with @ryanfeeley 
Something to investigate: 

![image](https://cloud.githubusercontent.com/assets/128755/7964751/7d08c8ca-09e7-11e5-90f0-f1c25c0bda78.png)

https://app.datadoghq.com/dash/50871/fxa-content-server-front-end?live=true&page=0&is_auto=false&from_ts=1430754901513&to_ts=1433346901513&tile_size=m&tpl_var_env=prod&fullscreen=59533762

cc @rfk

**Comment by rfk** [comment]
I'm trying to sanity-check this against the data in Kibana, but it's proving difficult.  Using the dashboard here:

  https://kibana.fxa.us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Client%20Metrics

I cannot construct a successful mental model of kibana's query syntax and I couldn't replicate that graph.  However, I did notice that there are a lot of `verify-email.verification-success` events that do not have a corresponding `screen.verify-email` event.  This is a representative example:

```
event_durations:   7404,7569,25076,25226,25229
events:   verify-email.verification.success,screen.signup-complete,verify-email.verification.success,screen.signup-complete,signup-complete.refresh
```

I don't know the full flow of events we expect here, but could these represent successful verifications that are not triggering a `screen.verify_email` event?

**Comment by rfk** [comment]
The auth-server HTTP logs suggest that the vast majority of verification attempts succeed:

![screen shot 2015-06-04 at 15 15 24](https://cloud.githubusercontent.com/assets/34695/7977285/921fd2f4-0acc-11e5-9ca4-c79bf6585848.png)

I suspect some of those are duplicate verifications caused by people reloading the "successfully verified" page, like the poor soul identified over in https://github.com/mozilla/fxa-content-server/issues/2522.    Still, I'd expect a nearly-50% failure rate to be visible somehow in the HTTP status logs.

**Comment by vladikoff** [comment]
@rfk Okay for that DataDog graph we should use the new 
```log.event('verified', { email: account.email, uid: account.uid, locale: account.locale })``` event from the fxa-auth-server + some new signup event as well.

@ckolos How can we get to the data that was logged in fxa-auth-server logs to DataDog? Is the Heka magic in place by any chance?
