### ISSUE TITLE
Should changing password require me to reauthenticate sync?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#980]
If memory serves, changing the password forces me to reauthenticate sync. Please investigate.

**Comment by rfk** [comment]
Checking the code, `/password/change/finish` does wind up calling `resetAccount`, so as password change *should* revoke the `sessionToken` on other devices and force you to re-authenticate.  @ryanfeeley maybe you hit a delayed revoke due to waiting for the sync certificate to expire?

**Comment by rfk** [comment]
I just tried this myself, and it seems to be casued by the wait time between password change and sync token expiry.  Here's roughly what happens:

  * Sign in to sync in BrowserA and start syncing
    * BrowserA gets its sync node allocation and temporary creds for use on that node
  * Change your password in BrowserB
    * All existing session tokens on the account are revoked at this point
  * BrowserA's sync creds are still good, so it continues to happily sync
  * When BrowerA's creds expire after (I think?) half an hour, or when you restart BrowserA, it will attempt to generate a fresh set, discover that it's been kicked out of sync, and ask you to reconnect

So AFAICT things are working as expected, just slowly because we have to wait for sync credentials to expire.  If we get e.g. a SimplePush channel to our devices in the future, we may be able to push them a "you need to reconnect to sync" message and have it actioned quicker.

It's worth noting that BrowserA can still sync with other devices until its credentials expire.  This is different to the password-reset case, where BrowserA would wind up in its own isolated world syncing with itself until you reconnected it.

So...@ryanfeeley do you feel like there's more action we should take in this bug, or shall we close it in favour of more general sync/device push and responsiveness work?

**Comment by ryanfeeley** [comment]
I think as a security measure that **Change Password** is preferable to **Reset Password** as the latter wipes user data from the server. I would like it to happen more quickly because we are messaging users to change their password (even if the link goes to reset). Note that when I delete the sync password from the password manager, it almost instantly goes into **Reconnect to Sync**.

**Comment by rfk** [comment]
See also https://github.com/mozilla/fxa-auth-mailer/issues/51

**Comment by rfk** [comment]
>  Note that when I delete the sync password from the password manager, it almost instantly
> goes into Reconnect to Sync.

I would hope so :-)

But we're talking about a cross-device scenario here, right?  We currently don't have a good mechanism to notify other devices on the account that the credentials have been changed, they have to discover it by getting an auth error in the course of their usual sync activity.

> I would like it to happen more quickly because we are messaging users to change
> their password (even if the link goes to reset).

FWIW I don't think the password reset would ripple out to other devices any faster than a password change.

AFAICT we have two broad options for making this happen faster:

  * ship the device-list thing, and use push notifications to ping all connected devices
  * build some back-channel into the sync servers so they can immediately revoke the device's sync credentials, rather than waiting for them to time out.

> When BrowerA's creds expire after (I think?) half an hour

Checking production config, it's actually a full hour before the device will be forced to reconnect.  We can probably drop it some, but not low enough that the effect would appear to be instantaneous.

**Comment by rfk** [comment]
Doing this better will likely depend on push or other instantaneous revokation mechanisms, so I don't think we can do anything more useful with this bug for now.  Closing it out.
